
/*
 * Copyright (c) 2025-2026 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

#include "../tool_settings.h"

#ifndef GFXRECON_COMPRESS_SETTINGS_H
#define GFXRECON_COMPRESS_SETTINGS_H

static void PrintUsage(const char* exe_name)
{
    std::string app_name     = exe_name;
    size_t      dir_location = app_name.find_last_of("/\\");

    if (dir_location >= 0)
    {
        app_name.replace(0, dir_location + 1, "");
    }

    GFXRECON_WRITE_CONSOLE("\n%s - A tool to compress/decompress GFXReconstruct capture files.\n", app_name.c_str());
    GFXRECON_WRITE_CONSOLE("Usage:");

    // Generate a vector to attach all available options for this
    // current platform.  Since it can vary per platform, we do not
    // generate the strings until we take the defines into account.
    std::vector<std::string> high_level_usage;
    high_level_usage.push_back("    " + app_name + "\t");
    high_level_usage.push_back("[--log-level <level>] ");
#if defined(WIN32)
    high_level_usage.push_back("[--no-debug-popup] ");
#endif // defined(WIN32)

    high_level_usage.push_back("<input_file> ");
    high_level_usage.push_back("<output_file> ");
    high_level_usage.push_back("<compression_format>");

    // Output the high-level usage to no more than 80 chars per line
    std::string output_string;
    const char new_line_start[] = "\t\t\t";
    for (auto& usage_item : high_level_usage)
    {
        if (output_string.length() + usage_item.length() > 80)
        {
            GFXRECON_WRITE_CONSOLE(output_string.c_str());
            output_string = new_line_start;
        }
        output_string += usage_item;
    }
    if (output_string.length() > strlen(new_line_start))
    {
       GFXRECON_WRITE_CONSOLE(output_string.c_str());
    }

    GFXRECON_WRITE_CONSOLE("\nRequired arguments:");
    GFXRECON_WRITE_CONSOLE("  <input_file>		Path to the input file to process.");
    GFXRECON_WRITE_CONSOLE("  <output_file>		Path to the output file to generate.");
    GFXRECON_WRITE_CONSOLE("  <compression_format>	Compression format to apply to the output file.");
    GFXRECON_WRITE_CONSOLE("\nOptional arguments:");
    GFXRECON_WRITE_CONSOLE("  --log-level <level>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify the highest level message to log.  The specified");
    GFXRECON_WRITE_CONSOLE("          \t\tlevel and all levels listed after it will be enabled for");
    GFXRECON_WRITE_CONSOLE("          \t\tlogging.  For example, choosing the `warning` level will");
    GFXRECON_WRITE_CONSOLE("          \t\talso enable the `error` and `fatal` levels.");
    GFXRECON_WRITE_CONSOLE("          \t\t<level> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `debug`     Messages with debug-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `info`      Messages with info-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `warning`   Messages with warning-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `error`     Only Error/Fatal messages");
    GFXRECON_WRITE_CONSOLE("          \t\t   `fatal`     Only Fatal messages");
#if defined(WIN32)
    GFXRECON_WRITE_CONSOLE("  --no-debug-popup");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows Only] Disable the 'Abort, Retry, Ignore' message");
    GFXRECON_WRITE_CONSOLE("          \t\tbox displayed when abort() is called (Windows debug only).");
#endif // defined(WIN32)
}
#endif // GFXRECON_COMPRESS_SETTINGS_H
