
/*
 * Copyright (c) 2025-2026 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

#include "../tool_settings.h"

#ifndef GFXRECON_TOCPP_SETTINGS_H
#define GFXRECON_TOCPP_SETTINGS_H

static void PrintUsage(const char* exe_name)
{
    std::string app_name     = exe_name;
    size_t      dir_location = app_name.find_last_of("/\\");

    if (dir_location >= 0)
    {
        app_name.replace(0, dir_location + 1, "");
    }

    GFXRECON_WRITE_CONSOLE("\n%s - A tool to convert GFXReconstruct capture files to Vulkan source.\n", app_name.c_str());
    GFXRECON_WRITE_CONSOLE("Usage:");

    // Generate a vector to attach all available options for this
    // current platform.  Since it can vary per platform, we do not
    // generate the strings until we take the defines into account.
    std::vector<std::string> high_level_usage;
    high_level_usage.push_back("    " + app_name + "\t");
    high_level_usage.push_back("-a|--android-template <dir> ");
    high_level_usage.push_back("-o|--output <dir> ");
    high_level_usage.push_back("[-c|--command-limit <num_commands>] ");
    high_level_usage.push_back("[-d|--max-window-dimensions <width,height>] ");
    high_level_usage.push_back("[-f|--frame-limit <num_frames>] ");
    high_level_usage.push_back("[-s|--captured-swapchain] ");
    high_level_usage.push_back("[-t|--target <platform>] ");

    high_level_usage.push_back("<capture_file>");

    // Output the high-level usage to no more than 80 chars per line
    std::string output_string;
    const char new_line_start[] = "\t\t\t";
    for (auto& usage_item : high_level_usage)
    {
        if (output_string.length() + usage_item.length() > 80)
        {
            GFXRECON_WRITE_CONSOLE(output_string.c_str());
            output_string = new_line_start;
        }
        output_string += usage_item;
    }
    if (output_string.length() > strlen(new_line_start))
    {
       GFXRECON_WRITE_CONSOLE(output_string.c_str());
    }

    GFXRECON_WRITE_CONSOLE("\nRequired arguments:");
    GFXRECON_WRITE_CONSOLE("   <capture_file>\t\tPath to a valid GFXReconstruct capture file to be converted");
    GFXRECON_WRITE_CONSOLE("  -a|--android-template <dir>");
    GFXRECON_WRITE_CONSOLE("          \t\tDirectory path containing the Android application template");
    GFXRECON_WRITE_CONSOLE("          \t\tfiles. [Only required if generating for Android]");
    GFXRECON_WRITE_CONSOLE("  -o|--output <dir>");
    GFXRECON_WRITE_CONSOLE("          \t\tDirectory path where the output will be generated into.");
    GFXRECON_WRITE_CONSOLE("\nOptional arguments:");
    GFXRECON_WRITE_CONSOLE("  -c|--command-limit <num_commands>");
    GFXRECON_WRITE_CONSOLE("          \t\tMaximum number of API commands recorded per C++ file. The");
    GFXRECON_WRITE_CONSOLE("          \t\tintent is to adjust compilation load per file. (Defaults to");
    GFXRECON_WRITE_CONSOLE("          \t\t1000 commands per file)");
    GFXRECON_WRITE_CONSOLE("  -d|--max-window-dimensions <width,height>");
    GFXRECON_WRITE_CONSOLE("          \t\tMaximum dimensions of the created window. (For example '-d");
    GFXRECON_WRITE_CONSOLE("          \t\t<width>,<height>')");
    GFXRECON_WRITE_CONSOLE("  -f|--frame-limit <num_frames>");
    GFXRECON_WRITE_CONSOLE("          \t\tMaximum number of frames to convert to C++ code from the");
    GFXRECON_WRITE_CONSOLE("          \t\tcapture file.");
    GFXRECON_WRITE_CONSOLE("  -s|--captured-swapchain");
    GFXRECON_WRITE_CONSOLE("          \t\tUse the swapchain as it was captured during toCpp replay");
    GFXRECON_WRITE_CONSOLE("          \t\tinstead of using the `Virtual Swapchain` path.");
    GFXRECON_WRITE_CONSOLE("  -t|--target <platform>");
    GFXRECON_WRITE_CONSOLE("          \t\tForce replay to use the specified wsi platform.");
    GFXRECON_WRITE_CONSOLE("          \t\t<platform> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `android`   Generate for Android usage");
    GFXRECON_WRITE_CONSOLE("          \t\t   `xcb`       Generate for XCB (only valid for Linux)");
    GFXRECON_WRITE_CONSOLE("          \t\t   `wayland`   Generate for Wayland (only valid for Linux)");
}
#endif // GFXRECON_TOCPP_SETTINGS_H
