
/*
 * Copyright (c) 2025-2026 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

#include "../tool_settings.h"

#ifndef GFXRECON_REPLAY_SETTINGS_H
#define GFXRECON_REPLAY_SETTINGS_H

static void PrintUsage(const char* exe_name)
{
    std::string app_name     = exe_name;
    size_t      dir_location = app_name.find_last_of("/\\");

    if (dir_location >= 0)
    {
        app_name.replace(0, dir_location + 1, "");
    }

    GFXRECON_WRITE_CONSOLE("\n%s - A tool to replay GFXReconstruct capture files.\n", app_name.c_str());
    GFXRECON_WRITE_CONSOLE("Usage:");

    // Generate a vector to attach all available options for this
    // current platform.  Since it can vary per platform, we do not
    // generate the strings until we take the defines into account.
    std::vector<std::string> high_level_usage;
    high_level_usage.push_back("    " + app_name + "\t");
    high_level_usage.push_back("[--log-file <log_file>] ");
    high_level_usage.push_back("[--log-level <level>] ");
    high_level_usage.push_back("[--log-timestamps] ");
    high_level_usage.push_back("[--screenshot-dir <dir>] ");
    high_level_usage.push_back("[--screenshot-format <format>] ");
    high_level_usage.push_back("[--screenshots <range>] ");
    high_level_usage.push_back("[--screenshot-interval <N>] ");
    high_level_usage.push_back("[--add-new-pipeline-caches] ");
    high_level_usage.push_back("[--capture] ");
    high_level_usage.push_back("[--cpu-mask <binary-mask>] ");
    high_level_usage.push_back("[--debug-messenger-level <level>] ");
    high_level_usage.push_back("[--deduplicate-device] ");
    high_level_usage.push_back("[--dump-resources <args>] ");
    high_level_usage.push_back("[--dump-resources-before-draw] ");
    high_level_usage.push_back("[--dump-resources-dir <dir>] ");
    high_level_usage.push_back("[--dump-resources-dump-all-image-subresources] ");
    high_level_usage.push_back("[--dump-resources-dump-build-acceleration-structures-input-buffers] ");
    high_level_usage.push_back("[--dump-resources-dump-color-attachment-index <index>] ");
    high_level_usage.push_back("[--dump-resources-dump-depth-attachment] ");
    high_level_usage.push_back("[--dump-resources-dump-raw-images] ");
    high_level_usage.push_back("[--dump-resources-dump-separate-alpha] ");
    high_level_usage.push_back("[--dump-resources-dump-unused-vertex-bindings] ");
    high_level_usage.push_back("[--dump-resources-dump-vertex-index-buffers] ");
    high_level_usage.push_back("[--dump-resources-image-format <format>] ");
    high_level_usage.push_back("[--dump-resources-json-output-per-command] ");
    high_level_usage.push_back("[--dump-resources-scale <scale>] ");
    high_level_usage.push_back("[--flush-inside-measurement-range] ");
    high_level_usage.push_back("[--fmr|--flush-measurement-range] ");
    high_level_usage.push_back("[--gpu <index>] ");
    high_level_usage.push_back("[--gpu-group <index>] ");
    high_level_usage.push_back("[-h|--help] ");
    high_level_usage.push_back("[--input-capture <input_file>] ");
    high_level_usage.push_back("[--load-pipeline-cache <cache-file>] ");
    high_level_usage.push_back("[--log-debugview] ");
    high_level_usage.push_back("[--measurement-file <file>] ");
    high_level_usage.push_back("[--mfr|--measurement-frame-range <start_frame>-<end_frame>] ");
    high_level_usage.push_back("[-m|--memory-translation <mode>] ");
    high_level_usage.push_back("[--offscreen-swapchain-frame-boundary] ");
    high_level_usage.push_back("[--opcd|--omit-pipeline-cache-data] ");
    high_level_usage.push_back("[--pause-frame <frame>] ");
    high_level_usage.push_back("[--paused] ");
    high_level_usage.push_back("[--pbi-all] ");
    high_level_usage.push_back("[--pbis <index1,index2>] ");
    high_level_usage.push_back("[--pcj|--pipeline-creation-jobs <num_jobs>] ");
    high_level_usage.push_back("[--preload-measurement-range] ");
    high_level_usage.push_back("[--quit-after-frame <frame>] ");
    high_level_usage.push_back("[--qamr|--quit-after-measurement-range] ");
    high_level_usage.push_back("[--remove-unsupported] ");
    high_level_usage.push_back("[--replace-shaders <dir>] ");
    high_level_usage.push_back("[--save-pipeline-cache <cache-file>] ");
    high_level_usage.push_back("[--screenshot-all] ");
    high_level_usage.push_back("[--screenshot-ignore-FrameBoundaryANDROID] ");
    high_level_usage.push_back("[--screenshot-prefix <file-prefix>] ");
    high_level_usage.push_back("[--screenshot-scale <scale>] ");
    high_level_usage.push_back("[--screenshot-size <width>x<height>] ");
    high_level_usage.push_back("[--sfa|--skip-failed-allocations] ");
    high_level_usage.push_back("[--swapchain <mode>] ");
    high_level_usage.push_back("[--sync] ");
    high_level_usage.push_back("[--use-captured-swapchain-indices] ");
    high_level_usage.push_back("[--use-colorspace-fallback] ");
    high_level_usage.push_back("[--validate] ");
    high_level_usage.push_back("[--version] ");
    high_level_usage.push_back("[--vssb|--virtual-swapchain-skip-blit] ");
    high_level_usage.push_back("[--wait-before-present] ");
    high_level_usage.push_back("[--wsi <platform>] ");
    high_level_usage.push_back("[--debug-device-lost] ");
    high_level_usage.push_back("[--dcp|--discard-cached-psos] ");
    high_level_usage.push_back("[--dump-resources-modifiable-state-only] ");
    high_level_usage.push_back("[--dx12-ags-inject-markers] ");
    high_level_usage.push_back("[--dx12-override-object-names] ");
    high_level_usage.push_back("[--dx12-two-pass-replay] ");
    high_level_usage.push_back("[--dump-resources-binary-file-compression-type <compression-format>] ");
    high_level_usage.push_back("[--present-mode <mode>] ");
    high_level_usage.push_back("[--sgfr|--skip-get-fence-ranges <frame-ranges>] ");
    high_level_usage.push_back("[--sgfs|--skip-get-fence-status <status>] ");
    high_level_usage.push_back("[--surface-index <N>] ");
#if defined(__ANDROID__)
    high_level_usage.push_back("[--onhb|--omit-null-hardware-buffers] ");
#endif // defined(__ANDROID__)
#if defined(WIN32)
    high_level_usage.push_back("[--allowed-messages <messages>] ");
    high_level_usage.push_back("[--batching-memory-usage <percentage>] ");
    high_level_usage.push_back("[--denied-messages <messages>] ");
    high_level_usage.push_back("[--fw|--force-windowed <width,height>] ");
    high_level_usage.push_back("[--fwo|--force-windowed-origin <x,y>] ");
    high_level_usage.push_back("[--use-cached-psos] ");
    high_level_usage.push_back("[--create-dummy-allocations] ");
    high_level_usage.push_back("[--no-debug-popup] ");
#endif // defined(WIN32)

    high_level_usage.push_back("<file>");

    // Output the high-level usage to no more than 80 chars per line
    std::string output_string;
    const char new_line_start[] = "\t\t\t";
    for (auto& usage_item : high_level_usage)
    {
        if (output_string.length() + usage_item.length() > 80)
        {
            GFXRECON_WRITE_CONSOLE(output_string.c_str());
            output_string = new_line_start;
        }
        output_string += usage_item;
    }
    if (output_string.length() > strlen(new_line_start))
    {
       GFXRECON_WRITE_CONSOLE(output_string.c_str());
    }

    GFXRECON_WRITE_CONSOLE("\nRequired arguments:");
    GFXRECON_WRITE_CONSOLE("   <file>\t\tPath to the capture file to replay.");
    GFXRECON_WRITE_CONSOLE("\nOptional arguments:");
    GFXRECON_WRITE_CONSOLE("  --log-file <log_file>");
    GFXRECON_WRITE_CONSOLE("          \t\tWhen set, log messages will be written to a file at the");
    GFXRECON_WRITE_CONSOLE("          \t\tspecified location.");
    GFXRECON_WRITE_CONSOLE("  --log-level <level>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify the highest level message to log.  The specified");
    GFXRECON_WRITE_CONSOLE("          \t\tlevel and all levels listed after it will be enabled for");
    GFXRECON_WRITE_CONSOLE("          \t\tlogging.  For example, choosing the `warning` level will");
    GFXRECON_WRITE_CONSOLE("          \t\talso enable the `error` and `fatal` levels.");
    GFXRECON_WRITE_CONSOLE("          \t\t<level> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `debug`     Messages with debug-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `info`      Messages with info-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `warning`   Messages with warning-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `error`     Only Error/Fatal messages");
    GFXRECON_WRITE_CONSOLE("          \t\t   `fatal`     Only Fatal messages");
    GFXRECON_WRITE_CONSOLE("  --log-timestamps");
    GFXRECON_WRITE_CONSOLE("          \t\tOutput a timestamp in front of each log message.");
    GFXRECON_WRITE_CONSOLE("  --screenshot-dir <dir>");
    GFXRECON_WRITE_CONSOLE("          \t\tDirectory used where screenshots are saved to.  Default is");
    GFXRECON_WRITE_CONSOLE("          \t\tthe current working directory.");
    GFXRECON_WRITE_CONSOLE("  --screenshot-format <format>");
    GFXRECON_WRITE_CONSOLE("          \t\tImage file format to use when saving screenshots.");
    GFXRECON_WRITE_CONSOLE("          \t\t<format> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `bmp`       Bitmap File Format.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `png`       Portable Network Graphics Format.");
    GFXRECON_WRITE_CONSOLE("  --screenshots <range>");
    GFXRECON_WRITE_CONSOLE("          \t\tGenerate screenshots for the specified frames. Target");
    GFXRECON_WRITE_CONSOLE("          \t\tframes are specified as a comma separated list of frame");
    GFXRECON_WRITE_CONSOLE("          \t\tranges.  A frame range can be specified as a single value,");
    GFXRECON_WRITE_CONSOLE("          \t\tto specify a single frame, or as two hyphenated values, to");
    GFXRECON_WRITE_CONSOLE("          \t\tspecify the first and last frames to process.  Frame ranges");
    GFXRECON_WRITE_CONSOLE("          \t\tshould be specified in ascending order and cannot overlap. ");
    GFXRECON_WRITE_CONSOLE("          \t\tNote that frame numbering is 1-based (i.e. the first frame");
    GFXRECON_WRITE_CONSOLE("          \t\tis frame 1). Example: 200,301-305 will generate six");
    GFXRECON_WRITE_CONSOLE("          \t\tscreenshots.");
    GFXRECON_WRITE_CONSOLE("  --screenshot-interval <N>");
    GFXRECON_WRITE_CONSOLE("          \t\tSets the number between every screenshot taken.  1 means");
    GFXRECON_WRITE_CONSOLE("          \t\tevery frame is screenshot, 2 means every other, etc.");
    GFXRECON_WRITE_CONSOLE("          \t\tExample: If screenshot range is 10-15 and interval is 2,");
    GFXRECON_WRITE_CONSOLE("          \t\tscreenshot will be generated for frames 10, 12 and 14.");
    GFXRECON_WRITE_CONSOLE("  --add-new-pipeline-caches");
    GFXRECON_WRITE_CONSOLE("          \t\tIf set, allows gfxreconstruct to create new vkPipelineCache");
    GFXRECON_WRITE_CONSOLE("          \t\tobjects when it encounters a pipeline created without");
    GFXRECON_WRITE_CONSOLE("          \t\tcache. This option can be used in coordination with");
    GFXRECON_WRITE_CONSOLE("          \t\t`--save-pipeline-cache` and `--load-pipeline-cache`.");
    GFXRECON_WRITE_CONSOLE("  --capture");
    GFXRECON_WRITE_CONSOLE("          \t\tCapture the replaying GFXR file. Capture uses the same log");
    GFXRECON_WRITE_CONSOLE("          \t\toptions as replay. All other capture option behavior and");
    GFXRECON_WRITE_CONSOLE("          \t\tusage is the same as when capturing with the GFXR layer.");
    GFXRECON_WRITE_CONSOLE("          \t\tThe capture functionality is included in the");
    GFXRECON_WRITE_CONSOLE("          \t\t`gfxrecon-replay` executable -- no GFXR capture layer is");
    GFXRECON_WRITE_CONSOLE("          \t\tadded to the Vulkan layer chain.");
    GFXRECON_WRITE_CONSOLE("  --cpu-mask <binary-mask>");
    GFXRECON_WRITE_CONSOLE("          \t\tSet of CPU cores used by the replayer. `binary-mask` is a");
    GFXRECON_WRITE_CONSOLE("          \t\tsuccession of '0' and '1' read from left to right that");
    GFXRECON_WRITE_CONSOLE("          \t\tspecifies used/unused cores. For example '10010' activates");
    GFXRECON_WRITE_CONSOLE("          \t\tthe first and fourth cores and deactivate all other cores.");
    GFXRECON_WRITE_CONSOLE("          \t\tIf the option is not set, all cores can be used. If the");
    GFXRECON_WRITE_CONSOLE("          \t\toption is set only for some cores, the other cores are not");
    GFXRECON_WRITE_CONSOLE("          \t\tused.");
    GFXRECON_WRITE_CONSOLE("  --debug-messenger-level <level>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify highest debug messenger severity level. Options");
    GFXRECON_WRITE_CONSOLE("          \t\tare: debug, info, warning, and error.");
    GFXRECON_WRITE_CONSOLE("          \t\t<level> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `debug`     Messages with debug-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `info`      Messages with info-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `warning`   Messages with warning-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `error`     Only Error/Fatal messages");
    GFXRECON_WRITE_CONSOLE("          \t\t   `fatal`     Only Fatal messages");
    GFXRECON_WRITE_CONSOLE("  --deduplicate-device");
    GFXRECON_WRITE_CONSOLE("          \t\tIf set, at most one VkDevice will be created for each");
    GFXRECON_WRITE_CONSOLE("          \t\tVkPhysicalDevice for RenderDoc and DXVK case.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources <args>");
    GFXRECON_WRITE_CONSOLE("          \t\tDump out resources during replay");
    GFXRECON_WRITE_CONSOLE("          \t\t<args> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   <submit-index,command-index,draw-call-index> The capture");
    GFXRECON_WRITE_CONSOLE("          \t\t                file will be examined, and");
    GFXRECON_WRITE_CONSOLE("          \t\t                <submit-index,command-index,draw-call-index>");
    GFXRECON_WRITE_CONSOLE("          \t\t                will be used to dump resources for the");
    GFXRECON_WRITE_CONSOLE("          \t\t                given submit, command and draw indices.");
    GFXRECON_WRITE_CONSOLE("          \t\t   <filename> Extract `--dump-resources` block indices args");
    GFXRECON_WRITE_CONSOLE("          \t\t                from the specified json file (must end in");
    GFXRECON_WRITE_CONSOLE("          \t\t                .json). The format for the json file is");
    GFXRECON_WRITE_CONSOLE("          \t\t                documented in detail in the gfxreconstruct");
    GFXRECON_WRITE_CONSOLE("          \t\t                documentation.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-before-draw");
    GFXRECON_WRITE_CONSOLE("          \t\tIn addition to dumping GPU resources after the draw calls");
    GFXRECON_WRITE_CONSOLE("          \t\tspecified by the `--dump-resources` argument, also dump");
    GFXRECON_WRITE_CONSOLE("          \t\tresources before the draw calls.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dir <dir>");
    GFXRECON_WRITE_CONSOLE("          \t\tDirectory to write dump resources output files. Default is");
    GFXRECON_WRITE_CONSOLE("          \t\tthe current working directory.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-all-image-subresources");
    GFXRECON_WRITE_CONSOLE("          \t\tDump all available mip levels and layers when dumping");
    GFXRECON_WRITE_CONSOLE("          \t\timages.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-build-acceleration-structures-input-buffers");
    GFXRECON_WRITE_CONSOLE("          \t\tDump all input buffers used in");
    GFXRECON_WRITE_CONSOLE("          \t\tvkCmdBuildAccelerationStructures. This includes vertex,");
    GFXRECON_WRITE_CONSOLE("          \t\tindex, transformation matrix, AABB and instance buffers.");
    GFXRECON_WRITE_CONSOLE("          \t\tDefault is off.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-color-attachment-index <index>");
    GFXRECON_WRITE_CONSOLE("          \t\tConfigures which color attachment to dump when dumping draw");
    GFXRECON_WRITE_CONSOLE("          \t\tcalls.  Default is all attachments.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-depth-attachment");
    GFXRECON_WRITE_CONSOLE("          \t\tConfigures whether to dump the depth attachment of draw");
    GFXRECON_WRITE_CONSOLE("          \t\tcalls. Default is false.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-raw-images");
    GFXRECON_WRITE_CONSOLE("          \t\tDump the images in raw format (without conversion),");
    GFXRECON_WRITE_CONSOLE("          \t\totherwise they will be transformed into a");
    GFXRECON_WRITE_CONSOLE("          \t\tVK_FORMAT_B8G8R8A8_* format, more suitable for dumping in");
    GFXRECON_WRITE_CONSOLE("          \t\tan image file.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-separate-alpha");
    GFXRECON_WRITE_CONSOLE("          \t\tDump the image alpha as a separate file from the main");
    GFXRECON_WRITE_CONSOLE("          \t\timage.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-unused-vertex-bindings");
    GFXRECON_WRITE_CONSOLE("          \t\tDump a vertex binding even if no vertex attributes");
    GFXRECON_WRITE_CONSOLE("          \t\treferences it.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-dump-vertex-index-buffers");
    GFXRECON_WRITE_CONSOLE("          \t\tEnable dumping of vertex and index buffers while dumping");
    GFXRECON_WRITE_CONSOLE("          \t\tdraw call resources. Default is disabled.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-image-format <format>");
    GFXRECON_WRITE_CONSOLE("          \t\tImage file format to use when dumping image resources.");
    GFXRECON_WRITE_CONSOLE("          \t\tAvailable formats are: bmp, png.");
    GFXRECON_WRITE_CONSOLE("          \t\t<format> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `bmp`       Bitmap File Format.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `png`       Portable Network Graphics Format.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-json-output-per-command");
    GFXRECON_WRITE_CONSOLE("          \t\tEnable storing a json output file for each dumped command. ");
    GFXRECON_WRITE_CONSOLE("          \t\tOverrides default behavior which is generating one output");
    GFXRECON_WRITE_CONSOLE("          \t\tjson file that contains the information for all dumped");
    GFXRECON_WRITE_CONSOLE("          \t\tcommands.");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-scale <scale>");
    GFXRECON_WRITE_CONSOLE("          \t\tScale images generated by dump resources by the given scale");
    GFXRECON_WRITE_CONSOLE("          \t\tfactor. The scale factor must be a floating point number");
    GFXRECON_WRITE_CONSOLE("          \t\tgreater than 0. Values greater than 10 are capped at 10.");
    GFXRECON_WRITE_CONSOLE("          \t\tDefault value is 1.0.");
    GFXRECON_WRITE_CONSOLE("  --flush-inside-measurement-range");
    GFXRECON_WRITE_CONSOLE("          \t\tIf this is specified the replayer will flush and wait for");
    GFXRECON_WRITE_CONSOLE("          \t\tall current GPU work to finish at the end of each frame");
    GFXRECON_WRITE_CONSOLE("          \t\tinside the measurement range.");
    GFXRECON_WRITE_CONSOLE("  --fmr|--flush-measurement-range");
    GFXRECON_WRITE_CONSOLE("          \t\tIf this is specified the replayer will flush and wait for");
    GFXRECON_WRITE_CONSOLE("          \t\tall current GPU work to finish at the start and end of the");
    GFXRECON_WRITE_CONSOLE("          \t\tmeasurement range.");
    GFXRECON_WRITE_CONSOLE("  --gpu <index>");
    GFXRECON_WRITE_CONSOLE("          \t\tUse the specified device for replay, where index is the");
    GFXRECON_WRITE_CONSOLE("          \t\tzero-based index to the array of physical devices returned");
    GFXRECON_WRITE_CONSOLE("          \t\tby vkEnumeratePhysicalDevices or");
    GFXRECON_WRITE_CONSOLE("          \t\tIDXGIFactory1::EnumAdapters1. Replay may fail if the");
    GFXRECON_WRITE_CONSOLE("          \t\tspecified device is not compatible with the original");
    GFXRECON_WRITE_CONSOLE("          \t\tcapture devices.");
    GFXRECON_WRITE_CONSOLE("  --gpu-group <index>");
    GFXRECON_WRITE_CONSOLE("          \t\tUse the specified device group for replay, where index is");
    GFXRECON_WRITE_CONSOLE("          \t\tthe zero-based index to the array of physical device group");
    GFXRECON_WRITE_CONSOLE("          \t\treturned by vkEnumeratePhysicalDeviceGroups.  Replay may");
    GFXRECON_WRITE_CONSOLE("          \t\tfail if the specified device group is not compatible with");
    GFXRECON_WRITE_CONSOLE("          \t\tthe original capture device group.");
    GFXRECON_WRITE_CONSOLE("  -h|--help");
    GFXRECON_WRITE_CONSOLE("          \t\tPrint usage information and exit");
    GFXRECON_WRITE_CONSOLE("  --input-capture <input_file>");
    GFXRECON_WRITE_CONSOLE("          \t\tThe name of the capture file to use for processing.  This");
    GFXRECON_WRITE_CONSOLE("          \t\toverrides the non-tagged input filename that used to appear");
    GFXRECON_WRITE_CONSOLE("          \t\tafter all optional arguments");
    GFXRECON_WRITE_CONSOLE("  --load-pipeline-cache <cache-file>");
    GFXRECON_WRITE_CONSOLE("          \t\tIf set, loads data created by the `--save-pipeline-cache`");
    GFXRECON_WRITE_CONSOLE("          \t\toption in <cache-file> and uses it to create the pipelines");
    GFXRECON_WRITE_CONSOLE("          \t\tinstead of the pipeline caches saved at capture time.");
    GFXRECON_WRITE_CONSOLE("  --log-debugview");
    GFXRECON_WRITE_CONSOLE("          \t\tLog messages with OutputDebugStringA.");
    GFXRECON_WRITE_CONSOLE("  --measurement-file <file>");
    GFXRECON_WRITE_CONSOLE("          \t\tWrite measurements to a file at the specified path. Default");
    GFXRECON_WRITE_CONSOLE("          \t\tis: '/sdcard/gfxrecon-measurements.json' on Android");
    GFXRECON_WRITE_CONSOLE("          \t\tand'./gfxrecon-measurements.json' on desktop.");
    GFXRECON_WRITE_CONSOLE("  --mfr|--measurement-frame-range <start_frame>-<end_frame>");
    GFXRECON_WRITE_CONSOLE("          \t\tCustom framerange to measure FPS for. This range will");
    GFXRECON_WRITE_CONSOLE("          \t\tinclude the start frame but not the end frame. The");
    GFXRECON_WRITE_CONSOLE("          \t\tmeasurement frame range defaults to all frames except the");
    GFXRECON_WRITE_CONSOLE("          \t\tloading frame but can be configured for any range. If the");
    GFXRECON_WRITE_CONSOLE("          \t\tend frame is past the last frame in the trace it will be");
    GFXRECON_WRITE_CONSOLE("          \t\tclamped to the frame after the last (so in that case the");
    GFXRECON_WRITE_CONSOLE("          \t\tresults would include the last frame).");
    GFXRECON_WRITE_CONSOLE("  -m|--memory-translation <mode>");
    GFXRECON_WRITE_CONSOLE("          \t\tEnable memory translation for replay on GPUs with memory");
    GFXRECON_WRITE_CONSOLE("          \t\ttypes that are not compatible with the capture GPU's memory");
    GFXRECON_WRITE_CONSOLE("          \t\ttypes");
    GFXRECON_WRITE_CONSOLE("          \t\t<mode> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `none`      No memory translation is performed");
    GFXRECON_WRITE_CONSOLE("          \t\t               (Default).");
    GFXRECON_WRITE_CONSOLE("          \t\t   `remap`     Attempt to map capture memory types to");
    GFXRECON_WRITE_CONSOLE("          \t\t               compatible replay memory types, without");
    GFXRECON_WRITE_CONSOLE("          \t\t               altering memory allocation behavior.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `realign`   Adjust memory allocation sizes and resource");
    GFXRECON_WRITE_CONSOLE("          \t\t               binding offsets based on replay memory");
    GFXRECON_WRITE_CONSOLE("          \t\t               properties.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `rebind`    Change memory allocation behavior based on");
    GFXRECON_WRITE_CONSOLE("          \t\t               resource usage and replay memory properties.");
    GFXRECON_WRITE_CONSOLE("          \t\t                Resources may be bound to different");
    GFXRECON_WRITE_CONSOLE("          \t\t               allocations with different offsets.  Uses");
    GFXRECON_WRITE_CONSOLE("          \t\t               VMA to manage allocations and");
    GFXRECON_WRITE_CONSOLE("          \t\t               suballocations.");
    GFXRECON_WRITE_CONSOLE("  --offscreen-swapchain-frame-boundary");
    GFXRECON_WRITE_CONSOLE("          \t\tShould only be used with offscreen swapchain. Activates the");
    GFXRECON_WRITE_CONSOLE("          \t\textension VK_EXT_frame_boundary (always supported if");
    GFXRECON_WRITE_CONSOLE("          \t\ttrimming, checks for driver support otherwise) and inserts");
    GFXRECON_WRITE_CONSOLE("          \t\tcommand buffer submission with VkFrameBoundaryEXT where");
    GFXRECON_WRITE_CONSOLE("          \t\tvkQueuePresentKHR was called in the original capture.  This");
    GFXRECON_WRITE_CONSOLE("          \t\tallows preserving frames when capturing a replay that uses");
    GFXRECON_WRITE_CONSOLE("          \t\toffscreen swapchain.");
    GFXRECON_WRITE_CONSOLE("  --opcd|--omit-pipeline-cache-data");
    GFXRECON_WRITE_CONSOLE("          \t\tOmit pipeline cache data from calls to");
    GFXRECON_WRITE_CONSOLE("          \t\tvkCreatePipelineCache and skip calls to");
    GFXRECON_WRITE_CONSOLE("          \t\tvkGetPipelineCacheData");
    GFXRECON_WRITE_CONSOLE("  --pause-frame <frame>");
    GFXRECON_WRITE_CONSOLE("          \t\tPause after replay frame number <frame>");
    GFXRECON_WRITE_CONSOLE("  --paused");
    GFXRECON_WRITE_CONSOLE("          \t\tPause after replaying the first frame (same as");
    GFXRECON_WRITE_CONSOLE("          \t\t`--pause-frame 1`).");
    GFXRECON_WRITE_CONSOLE("  --pbi-all");
    GFXRECON_WRITE_CONSOLE("          \t\tPrint all block information.");
    GFXRECON_WRITE_CONSOLE("  --pbis <index1,index2>");
    GFXRECON_WRITE_CONSOLE("          \t\tPrint block information between block index1 and block");
    GFXRECON_WRITE_CONSOLE("          \t\tindex2.");
    GFXRECON_WRITE_CONSOLE("  --pcj|--pipeline-creation-jobs <num_jobs>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify the number of asynchronous pipeline-creation jobs");
    GFXRECON_WRITE_CONSOLE("          \t\tas integer. If <num_jobs> is negative it will be added to");
    GFXRECON_WRITE_CONSOLE("          \t\tthe number of cpu-cores Default: 0 (do not use asynchronous");
    GFXRECON_WRITE_CONSOLE("          \t\toperations).");
    GFXRECON_WRITE_CONSOLE("  --preload-measurement-range");
    GFXRECON_WRITE_CONSOLE("          \t\tPreload the provided measurement range of frames.");
    GFXRECON_WRITE_CONSOLE("  --quit-after-frame <frame>");
    GFXRECON_WRITE_CONSOLE("          \t\tQuit replay after frame <frame> has completed.");
    GFXRECON_WRITE_CONSOLE("  --qamr|--quit-after-measurement-range");
    GFXRECON_WRITE_CONSOLE("          \t\tIf this is specified the replayer will abort when it");
    GFXRECON_WRITE_CONSOLE("          \t\treaches the <end_frame> specified in the");
    GFXRECON_WRITE_CONSOLE("          \t\t`--measurement-frame-range` argument.");
    GFXRECON_WRITE_CONSOLE("  --remove-unsupported");
    GFXRECON_WRITE_CONSOLE("          \t\tRemove unsupported extensions and features from instance");
    GFXRECON_WRITE_CONSOLE("          \t\tand device creation parameters.");
    GFXRECON_WRITE_CONSOLE("  --replace-shaders <dir>");
    GFXRECON_WRITE_CONSOLE("          \t\tReplace the shader code in each CreateShaderModule with the");
    GFXRECON_WRITE_CONSOLE("          \t\tcontents of the file <dir>/sh<handle_id> if found, where");
    GFXRECON_WRITE_CONSOLE("          \t\t<handle_id> is the handle id of the CreateShaderModule");
    GFXRECON_WRITE_CONSOLE("          \t\tcall. See gfxrecon-extract.");
    GFXRECON_WRITE_CONSOLE("  --save-pipeline-cache <cache-file>");
    GFXRECON_WRITE_CONSOLE("          \t\tIf set, produces pipeline caches at replay time instead of");
    GFXRECON_WRITE_CONSOLE("          \t\tusing the one saved at capture time and save those caches");
    GFXRECON_WRITE_CONSOLE("          \t\tin <cache-file>");
    GFXRECON_WRITE_CONSOLE("  --screenshot-all");
    GFXRECON_WRITE_CONSOLE("          \t\tGenerate screenshots for all frames.  When this option is");
    GFXRECON_WRITE_CONSOLE("          \t\tspecified, other screenshot frame-related options are");
    GFXRECON_WRITE_CONSOLE("          \t\tignored.");
    GFXRECON_WRITE_CONSOLE("  --screenshot-ignore-FrameBoundaryANDROID");
    GFXRECON_WRITE_CONSOLE("          \t\tIf set, frames switched with vkFrameBoundANDROID will be");
    GFXRECON_WRITE_CONSOLE("          \t\tignored from the screenshot handler.");
    GFXRECON_WRITE_CONSOLE("  --screenshot-prefix <file-prefix>");
    GFXRECON_WRITE_CONSOLE("          \t\tPrefix to apply to the screenshot file name.  Default is");
    GFXRECON_WRITE_CONSOLE("          \t\t'screenshot', producing file names similar to");
    GFXRECON_WRITE_CONSOLE("          \t\t'screenshot_frame_8049.bmp'");
    GFXRECON_WRITE_CONSOLE("  --screenshot-scale <scale>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify a decimal factor which will determine screenshot");
    GFXRECON_WRITE_CONSOLE("          \t\tsizes. The factor will be multiplied with the swapchain");
    GFXRECON_WRITE_CONSOLE("          \t\timages dimension to determine the screenshot dimensions.");
    GFXRECON_WRITE_CONSOLE("          \t\tDefault value is 1.0.");
    GFXRECON_WRITE_CONSOLE("  --screenshot-size <width>x<height>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify desired screenshot dimensions. Leaving this");
    GFXRECON_WRITE_CONSOLE("          \t\tunspecified screenshots will use the swapchain images");
    GFXRECON_WRITE_CONSOLE("          \t\tdimensions. If `--screenshot-scale` is also specified then");
    GFXRECON_WRITE_CONSOLE("          \t\tthis option is ignored.");
    GFXRECON_WRITE_CONSOLE("  --sfa|--skip-failed-allocations");
    GFXRECON_WRITE_CONSOLE("          \t\tSkip vkAllocateMemory, vkAllocateCommandBuffers, and");
    GFXRECON_WRITE_CONSOLE("          \t\tvkAllocateDescriptorSets calls that failed during capture.");
    GFXRECON_WRITE_CONSOLE("  --swapchain <mode>");
    GFXRECON_WRITE_CONSOLE("          \t\tChoose a swapchain mode to replay.");
    GFXRECON_WRITE_CONSOLE("          \t\t<mode> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `captured`  Use the swapchain indices stored in the");
    GFXRECON_WRITE_CONSOLE("          \t\t               capture directly on the swapchain setup for");
    GFXRECON_WRITE_CONSOLE("          \t\t               replay.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `offscreen`  Disable creating swapchains, surfaces and");
    GFXRECON_WRITE_CONSOLE("          \t\t               windows. To see rendering, add the");
    GFXRECON_WRITE_CONSOLE("          \t\t               --screenshots option.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `virtual`   Virtual Swapchain of images which match the");
    GFXRECON_WRITE_CONSOLE("          \t\t               swapchain in effect at capture time and");
    GFXRECON_WRITE_CONSOLE("          \t\t               which are copied to the underlying swapchain");
    GFXRECON_WRITE_CONSOLE("          \t\t               of the implementation being replayed on");
    GFXRECON_WRITE_CONSOLE("          \t\t               (Default).");
    GFXRECON_WRITE_CONSOLE("  --sync");
    GFXRECON_WRITE_CONSOLE("          \t\tSynchronize after each queue submission with");
    GFXRECON_WRITE_CONSOLE("          \t\tvkQueueWaitIdle.");
    GFXRECON_WRITE_CONSOLE("  --use-captured-swapchain-indices");
    GFXRECON_WRITE_CONSOLE("          \t\tSame as `--swapchain captured`.  Ignored if the");
    GFXRECON_WRITE_CONSOLE("          \t\t`--swapchain` option is used.");
    GFXRECON_WRITE_CONSOLE("  --use-colorspace-fallback");
    GFXRECON_WRITE_CONSOLE("          \t\tSwap the swapchain color space if unsupported by replay");
    GFXRECON_WRITE_CONSOLE("          \t\tdevice. Check if color space is not supported by replay");
    GFXRECON_WRITE_CONSOLE("          \t\tdevice and fallback to VK_COLOR_SPACE_SRGB_NONLINEAR_KHR.");
    GFXRECON_WRITE_CONSOLE("  --validate");
    GFXRECON_WRITE_CONSOLE("          \t\tEnable the Khronos Vulkan validation layer when replaying a");
    GFXRECON_WRITE_CONSOLE("          \t\tVulkan capture or the Direct3D debug layer when replaying a");
    GFXRECON_WRITE_CONSOLE("          \t\tDirect3D 12 capture.");
    GFXRECON_WRITE_CONSOLE("  --version");
    GFXRECON_WRITE_CONSOLE("          \t\tPrint version information and exit.");
    GFXRECON_WRITE_CONSOLE("  --vssb|--virtual-swapchain-skip-blit");
    GFXRECON_WRITE_CONSOLE("          \t\tIf using Virtual Swapchain, skip the actual BLTs to the");
    GFXRECON_WRITE_CONSOLE("          \t\tactual HW surface to gain performance during replay.");
    GFXRECON_WRITE_CONSOLE("  --wait-before-present");
    GFXRECON_WRITE_CONSOLE("          \t\tForce wait on completion of queue operations for all queues");
    GFXRECON_WRITE_CONSOLE("          \t\tbefore calling Present. This is needed for accurate");
    GFXRECON_WRITE_CONSOLE("          \t\tacquisition of instrumentation data on some platforms.");
    GFXRECON_WRITE_CONSOLE("  --wsi <platform>");
    GFXRECON_WRITE_CONSOLE("          \t\tForce replay to use the specified wsi platform.");
    GFXRECON_WRITE_CONSOLE("          \t\t<platform> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `auto`      Automatically attempt to determine WSI used");
    GFXRECON_WRITE_CONSOLE("          \t\t               based on platform (Default).");
    GFXRECON_WRITE_CONSOLE("          \t\t   `win32`     Force WIN32 WSI type WSI (Valid on Windows).");
    GFXRECON_WRITE_CONSOLE("          \t\t   `xlib`      Force using XLIB WSI (Valid on Linux).");
    GFXRECON_WRITE_CONSOLE("          \t\t   `xcb`       Force using XCB WSI (Valid on Linux).");
    GFXRECON_WRITE_CONSOLE("          \t\t   `wayland`   Force using Wayland WSI (Valid on Linux).");
    GFXRECON_WRITE_CONSOLE("          \t\t   `display`   Force using Display WSI.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `headless`  Force using headless WSI.");
#if defined(__ANDROID__)
    GFXRECON_WRITE_CONSOLE("  --onhb|--omit-null-hardware-buffers");
    GFXRECON_WRITE_CONSOLE("          \t\t[Android Only] Omit calls that use a NULL AHardwareBuffer");
#endif // defined(__ANDROID__)
#if defined(WIN32)
    GFXRECON_WRITE_CONSOLE("  --create-dummy-allocations");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows Only] Enable creation of dummy heaps and resources");
    GFXRECON_WRITE_CONSOLE("          \t\tfor replay validation.");
    GFXRECON_WRITE_CONSOLE("  --no-debug-popup");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows Only] Disable the 'Abort, Retry, Ignore' message");
    GFXRECON_WRITE_CONSOLE("          \t\tbox displayed when abort() is called (Windows debug only).");
#endif // defined(WIN32)
    GFXRECON_WRITE_CONSOLE("**D3D12-Specific arguments:");
    GFXRECON_WRITE_CONSOLE("  --debug-device-lost");
    GFXRECON_WRITE_CONSOLE("          \t\t[D3D12 Only] Enables automatic injection of breadcrumbs");
    GFXRECON_WRITE_CONSOLE("          \t\tinto command buffers and page fault reporting. Used to");
    GFXRECON_WRITE_CONSOLE("          \t\tdebug device removed problems.");
    GFXRECON_WRITE_CONSOLE("  --dcp|--discard-cached-psos");
    GFXRECON_WRITE_CONSOLE("          \t\t[D3D12 Only] Discard cached PSOs [Deprecated, please use");
    GFXRECON_WRITE_CONSOLE("          \t\t'--use-cached-psos'].");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-modifiable-state-only");
    GFXRECON_WRITE_CONSOLE("          \t\t[D3D12 Only] Only dump resources that are in a modifiable");
    GFXRECON_WRITE_CONSOLE("          \t\tstate set by D3D12 ResourceBarrier.");
    GFXRECON_WRITE_CONSOLE("  --dx12-ags-inject-markers");
    GFXRECON_WRITE_CONSOLE("          \t\t[D3D12 Only] Label each API calls as block index of the");
    GFXRECON_WRITE_CONSOLE("          \t\ttrace Radeon GPU Detective could dump the label for");
    GFXRECON_WRITE_CONSOLE("          \t\tdebugging.");
    GFXRECON_WRITE_CONSOLE("  --dx12-override-object-names");
    GFXRECON_WRITE_CONSOLE("          \t\t[D3D12 Only] Generate unique names for all ID3D12Objects");
    GFXRECON_WRITE_CONSOLE("          \t\tand assign each object the generated name.  This is");
    GFXRECON_WRITE_CONSOLE("          \t\tintended to assist in replay debugging.");
    GFXRECON_WRITE_CONSOLE("  --dx12-two-pass-replay");
    GFXRECON_WRITE_CONSOLE("          \t\t[D3D12 Only] Enable D3D12 Two Pass Replay.");
#if defined(WIN32)
    GFXRECON_WRITE_CONSOLE("  --allowed-messages <messages>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows D3D12 Only] Identify messages to allow D3D12");
    GFXRECON_WRITE_CONSOLE("          \t\tdebugging to output");
    GFXRECON_WRITE_CONSOLE("  --batching-memory-usage <percentage>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows D3D12 Only] Max amount of memory consumption while");
    GFXRECON_WRITE_CONSOLE("          \t\tloading a trimmed capture file. Acceptable values range");
    GFXRECON_WRITE_CONSOLE("          \t\tfrom 0 to 100. 0 means no batching at all 100 means use all");
    GFXRECON_WRITE_CONSOLE("          \t\tavailable system and GPU memory");
    GFXRECON_WRITE_CONSOLE("  --denied-messages <messages>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows D3D12 Only] Identify messages to deny D3D12");
    GFXRECON_WRITE_CONSOLE("          \t\tdebugging to output");
    GFXRECON_WRITE_CONSOLE("  --fw|--force-windowed <width,height>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows D3D12 Only] Setup windowed and override");
    GFXRECON_WRITE_CONSOLE("          \t\tresolution.");
    GFXRECON_WRITE_CONSOLE("  --fwo|--force-windowed-origin <x,y>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows D3D12 Only] Setup windowed origin.");
    GFXRECON_WRITE_CONSOLE("  --use-cached-psos");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows D3D12 Only] Permit using cached PSOs when creating");
    GFXRECON_WRITE_CONSOLE("          \t\tgraphics or compute pipelines.  Using cached PSOs may");
    GFXRECON_WRITE_CONSOLE("          \t\treduce PSO creation time but may result in replay errors.");
#endif // defined(WIN32)
    GFXRECON_WRITE_CONSOLE("**Vulkan-Specific arguments:");
    GFXRECON_WRITE_CONSOLE("  --dump-resources-binary-file-compression-type <compression-format>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Vulkan Only] Compress files that are dumped as binary. ");
    GFXRECON_WRITE_CONSOLE("          \t\t<compression-format> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `lz4`       Fastest compression algorithm that favors");
    GFXRECON_WRITE_CONSOLE("          \t\t               performance over compression ratio.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `zlib`      Widely used compression algorithm with");
    GFXRECON_WRITE_CONSOLE("          \t\t               better compression ratio than LZ4 but worse");
    GFXRECON_WRITE_CONSOLE("          \t\t               performance.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `zstd`      Newer compression algorithm with better");
    GFXRECON_WRITE_CONSOLE("          \t\t               compression ratio and performance than ZLIB,");
    GFXRECON_WRITE_CONSOLE("          \t\t               though not as fast as LZ4.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `none`      No compression (Default)");
    GFXRECON_WRITE_CONSOLE("  --present-mode <mode>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Vulkan Only] Override the VkPresentModeKHR of the");
    GFXRECON_WRITE_CONSOLE("          \t\tswapchain value during replay");
    GFXRECON_WRITE_CONSOLE("          \t\t<mode> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `capture`   Use whatever present mode the original");
    GFXRECON_WRITE_CONSOLE("          \t\t               application used.");
    GFXRECON_WRITE_CONSOLE("          \t\t   `immediate`  Force VK_PRESENT_MODE_IMMEDIATE_KHR");
    GFXRECON_WRITE_CONSOLE("          \t\t   `mailbox`   Force VK_PRESENT_MODE_MAILBOX_KHR");
    GFXRECON_WRITE_CONSOLE("          \t\t   `fifo`      Force VK_PRESENT_MODE_FIFO_KHR");
    GFXRECON_WRITE_CONSOLE("          \t\t   `fifo_relaxed`  Force VK_PRESENT_MODE_FIFO_RELAXED_KHR");
    GFXRECON_WRITE_CONSOLE("  --sgfr|--skip-get-fence-ranges <frame-ranges>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Vulkan Only] Frame ranges where `--sgfs` applies. The");
    GFXRECON_WRITE_CONSOLE("          \t\tformat is:");
    GFXRECON_WRITE_CONSOLE("          \t\t<frame-start-1>-<frame-end-1>[,<frame-start-1>-<frame-end-1>]*");
    GFXRECON_WRITE_CONSOLE("  --sgfs|--skip-get-fence-status <status>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Vulkan Only] Specify behaviour to skip calls to");
    GFXRECON_WRITE_CONSOLE("          \t\tvkWaitForFences and vkGetFenceStatus. <status> = 0: Don't");
    GFXRECON_WRITE_CONSOLE("          \t\tskip, <status> = 1: Skip unsuccessful calls, <status> = 2:");
    GFXRECON_WRITE_CONSOLE("          \t\tAlways Skip. If no skip frame range is specified (through");
    GFXRECON_WRITE_CONSOLE("          \t\t`--sgfr`), the status applies to all frames. Skip");
    GFXRECON_WRITE_CONSOLE("          \t\tvkGetFenceStatus calls that return a provided status");
    GFXRECON_WRITE_CONSOLE("  --surface-index <N>");
    GFXRECON_WRITE_CONSOLE("          \t\t[Vulkan Only] Restrict rendering to the Nth surface object");
    GFXRECON_WRITE_CONSOLE("          \t\tcreated. Used with captures that include multiple surfaces.");
    GFXRECON_WRITE_CONSOLE("          \t\tDefault is -1 (render to all surfaces).");
}
#endif // GFXRECON_REPLAY_SETTINGS_H
