
/*
 * Copyright (c) 2025 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

#ifndef GFXRECON_SETTINGS_STRUCT_H
#define GFXRECON_SETTINGS_STRUCT_H

#include <cstdint>
#include <string>

struct GfxrCaptureSettingsStruct
{
    // clang-format off
    std::string capture_compression_type{"lz4"};
#if defined(__ANDROID__)
    std::string capture_file{"/sdcard/gfxrecon_capture.gfxr"};
#else
    std::string capture_file{"gfxrecon_capture.gfxr"};
#endif
    bool        capture_file_flush{false};
    bool        capture_file_timestamp{true};
    std::string capture_frames{""};
    std::string capture_process_name{""};
    std::string capture_queue_submits{""};
    bool        capture_dynamic_trigger{false};
    bool        capture_dynamic_trigger_dump_assets{false};
    std::string capture_trigger_frames{""};
    bool        capture_use_asset_file{false};
    bool        force_command_serialization{false};
    bool        log_allow_indents{false};
    bool        log_break_on_error{false};
    bool        log_detailed{false};
    bool        log_errors_to_stderr{true};
    std::string log_file{""};
    bool        log_file_create_new{true};
    bool        log_file_flush_after_write{false};
    bool        log_file_keep_open{true};
    std::string log_level{"info"};
    bool        log_output_to_console{true};
    bool        log_timestamps{false};
    std::string memory_tracking_mode{"page_guard"};
    bool        page_guard_copy_on_map{true};
    bool        page_guard_persistent_memory{false};
    bool        page_guard_separate_read{true};
    bool        page_guard_signal_handler_watcher{false};
    int32_t     page_guard_signal_handler_watcher_max_restores{1};
    bool        page_guard_unblock_sigsegv{false};
    bool        queue_zero_only{false};
    bool        quit_after_capture_frames{false};
#if defined(__ANDROID__)
    std::string screenshot_dir{"/sdcard"};
#else
    std::string screenshot_dir{""};
#endif
    std::string screenshot_format{"bmp"};
    std::string screenshot_frames{""};
    int32_t     screenshot_interval{1};

    // D3D12-Specific
    uint32_t    accel_struct_padding{0};
    std::string capture_draw_calls{""};
    bool        capture_iunknown_wrapping{false};
    bool        debug_device_lost{false};
    bool        debug_layer{false};
    bool        disable_dxr{false};
    bool        disable_meta_command{false};
    std::string rv_annotation_descriptor{""};
    bool        rv_annotation_experimental{false};
    std::string rv_annotation_gpuva{""};
    bool        rv_annotation_rand{false};

    // Vulkan-Specific
    bool        allow_pipeline_compile_required{false};
    bool        force_fifo_present_mode{true};
    bool        page_guard_align_buffer_sizes{true};
#if defined(__ANDROID__)
    bool        ignore_frame_boundary_android{false};
#endif // defined(__ANDROID__)
#if defined(__ANDROID__)
    bool        capture_android_dump_assets{false};
    bool        capture_android_trigger{false};
    bool        page_guard_track_ahb_memory{false};
#endif // defined(__ANDROID__)
#if defined(__linux__)
    std::string capture_environment{""};
    std::string capture_trigger{""};
#endif // defined(__linux__)
#if defined(__APPLE__)
    std::string capture_environment{""};
    std::string capture_trigger{""};
#endif // defined(__APPLE__)
#if defined(WIN32)
    std::string capture_environment{""};
    std::string capture_trigger{""};
    bool        log_output_to_os_debug_string{false};
    bool        page_guard_external_memory{false};
#endif // defined(WIN32)

    // OpenXR-Specific
    bool        skip_threads_with_invalid_data{false};

    // clang-format on
};

struct GfxrReplaySettingsStruct
{
    // clang-format off
    std::string log_file{""};
    std::string log_level{"info"};
    bool        log_timestamps{false};
#if defined(__ANDROID__)
    std::string screenshot_dir{"/sdcard"};
#else
    std::string screenshot_dir{""};
#endif
    std::string screenshot_format{"bmp"};
    std::string screenshots{""};
    int32_t     screenshot_interval{1};
    bool        add_new_pipeline_caches{false};
    bool        capture{false};
    std::string cpu_mask{""};
    std::string debug_messenger_level{"warning"};
    bool        deduplicate_device{false};
    std::string dump_resources{""};
    bool        dump_resources_before_draw{false};
    bool        dump_resources_dump_all_image_subresources{false};
    bool        dump_resources_dump_build_acceleration_structures_input_buffers{false};
    int32_t     dump_resources_dump_color_attachment_index{-1};
    bool        dump_resources_dump_depth_attachment{false};
    bool        dump_resources_dump_raw_images{false};
    bool        dump_resources_dump_separate_alpha{false};
    bool        dump_resources_dump_unused_vertex_bindings{false};
    bool        dump_resources_dump_vertex_index_buffers{false};
    std::string dump_resources_image_format{"bmp"};
    bool        dump_resources_json_output_per_command{false};
    float       dump_resources_scale{1.0f};
    bool        flush_inside_measurement_range{false};
    bool        flush_measurement_range{false};
    std::string gpu{""};
    std::string gpu_group{""};
    bool        help{false};
    std::string input_capture{""};
    std::string load_pipeline_cache{""};
    bool        log_debugview{false};
#if defined(__ANDROID__)
    std::string measurement_file{"/sdcard/gfxrecon-measurement.gfxr"};
#else
    std::string measurement_file{"gfxrecon-measurement.gfxr"};
#endif
    std::string measurement_frame_range{""};
    std::string memory_translation{"none"};
    bool        offscreen_swapchain_frame_boundary{false};
    bool        omit_pipeline_cache_data{false};
    int32_t     pause_frame{-1};
    bool        paused{false};
    bool        pbi_all{false};
    std::string pbis{""};
    int32_t     pipeline_creation_jobs{0};
    bool        preload_measurement_range{false};
    std::string quit_after_frame{""};
    bool        quit_after_measurement_range{false};
    bool        remove_unsupported{false};
    std::string replace_shaders{""};
    std::string save_pipeline_cache{""};
    bool        screenshot_all{false};
    bool        screenshot_ignore_FrameBoundaryANDROID{false};
    std::string screenshot_prefix{"screenshot"};
    float       screenshot_scale{1.0f};
    std::string screenshot_size{""};
    bool        skip_failed_allocations{false};
    std::string swapchain{"virtual"};
    bool        sync{false};
    bool        use_captured_swapchain_indices{false};
    bool        use_colorspace_fallback{false};
    bool        validate{false};
    bool        version{false};
    bool        virtual_swapchain_skip_blit{false};
    bool        wait_before_present{false};
    std::string wsi{"auto"};

    // D3D12-Specific
    bool        debug_device_lost{false};
    bool        discard_cached_psos{false};
#if defined(__ANDROID__)
    std::string dump_resources_dir{"/sdcard"};
#else
    std::string dump_resources_dir{""};
#endif
    bool        dump_resources_modifiable_state_only{false};
    bool        dx12_ags_inject_markers{false};
    bool        dx12_override_object_names{false};
    bool        dx12_two_pass_replay{false};
#if defined(WIN32)
    std::string allowed_messages{""};
    int32_t     batching_memory_usage{80};
    std::string denied_messages{""};
    std::string force_windowed{""};
    std::string force_windowed_origin{""};
    bool        use_cached_psos{false};
#endif // defined(WIN32)

    // Vulkan-Specific
    std::string dump_resources_binary_file_compression_type{"none"};
    std::string present_mode{"capture"};
    std::string skip_get_fence_ranges{""};
    int32_t     skip_get_fence_status{0};
    int32_t     surface_index{-1};
#if defined(__ANDROID__)
    bool        omit_null_hardware_buffers{false};
#endif // defined(__ANDROID__)
#if defined(WIN32)
    bool        create_dummy_allocations{false};
    bool        no_debug_popup{false};
#endif // defined(WIN32)

    // OpenXR-Specific

    // clang-format on
};

struct GfxrSettingsStruct
{
    // clang-format off
    GfxrCaptureSettingsStruct capture_settings;
    GfxrReplaySettingsStruct replay_settings;
    // clang-format on
};

#endif // GFXRECON_SETTINGS_STRUCT_H

