
/*
 * Copyright (c) 2025 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

// clang-format off


// This functions takes in a settings key value and a string from the Vulkan settings file
// and attempts to update the setting value associated with the key.
void SettingsManager::AdjustSettingFromFile(const std::string& key,
                                            const std::string& value)
{
    if (!key.compare("allow_pipeline_compile_required"))
    {
        settings_struct_.capture_settings.allow_pipeline_compile_required = SettingValueToBool(value);
    }
    else if (!key.compare("capture_compression_type"))
    {
        settings_struct_.capture_settings.capture_compression_type = value;
    }
    else if (!key.compare("capture_file"))
    {
        settings_struct_.capture_settings.capture_file = value;
    }
    else if (!key.compare("capture_file_flush"))
    {
        settings_struct_.capture_settings.capture_file_flush = SettingValueToBool(value);
    }
    else if (!key.compare("capture_file_timestamp"))
    {
        settings_struct_.capture_settings.capture_file_timestamp = SettingValueToBool(value);
    }
    else if (!key.compare("capture_frames"))
    {
        settings_struct_.capture_settings.capture_frames = value;
    }
    else if (!key.compare("capture_process_name"))
    {
        settings_struct_.capture_settings.capture_process_name = value;
    }
    else if (!key.compare("capture_queue_submits"))
    {
        settings_struct_.capture_settings.capture_queue_submits = value;
    }
    else if (!key.compare("capture_dynamic_trigger"))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger = SettingValueToBool(value);
    }
    else if (!key.compare("capture_dynamic_trigger_dump_assets"))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger_dump_assets = SettingValueToBool(value);
    }
    else if (!key.compare("capture_trigger_frames"))
    {
        settings_struct_.capture_settings.capture_trigger_frames = value;
    }
    else if (!key.compare("capture_use_asset_file"))
    {
        settings_struct_.capture_settings.capture_use_asset_file = SettingValueToBool(value);
    }
    else if (!key.compare("force_command_serialization"))
    {
        settings_struct_.capture_settings.force_command_serialization = SettingValueToBool(value);
    }
    else if (!key.compare("force_fifo_present_mode"))
    {
        settings_struct_.capture_settings.force_fifo_present_mode = SettingValueToBool(value);
    }
    else if (!key.compare("log_allow_indents"))
    {
        settings_struct_.capture_settings.log_allow_indents = SettingValueToBool(value);
    }
    else if (!key.compare("log_break_on_error"))
    {
        settings_struct_.capture_settings.log_break_on_error = SettingValueToBool(value);
    }
    else if (!key.compare("log_detailed"))
    {
        settings_struct_.capture_settings.log_detailed = SettingValueToBool(value);
    }
    else if (!key.compare("log_errors_to_stderr"))
    {
        settings_struct_.capture_settings.log_errors_to_stderr = SettingValueToBool(value);
    }
    else if (!key.compare("log_file"))
    {
        settings_struct_.capture_settings.log_file = value;
    }
    else if (!key.compare("log_file_create_new"))
    {
        settings_struct_.capture_settings.log_file_create_new = SettingValueToBool(value);
    }
    else if (!key.compare("log_file_flush_after_write"))
    {
        settings_struct_.capture_settings.log_file_flush_after_write = SettingValueToBool(value);
    }
    else if (!key.compare("log_file_keep_open"))
    {
        settings_struct_.capture_settings.log_file_keep_open = SettingValueToBool(value);
    }
    else if (!key.compare("log_level"))
    {
        settings_struct_.capture_settings.log_level = value;
    }
    else if (!key.compare("log_output_to_console"))
    {
        settings_struct_.capture_settings.log_output_to_console = SettingValueToBool(value);
    }
    else if (!key.compare("log_timestamps"))
    {
        settings_struct_.capture_settings.log_timestamps = SettingValueToBool(value);
    }
    else if (!key.compare("memory_tracking_mode"))
    {
        settings_struct_.capture_settings.memory_tracking_mode = value;
    }
    else if (!key.compare("page_guard_align_buffer_sizes"))
    {
        settings_struct_.capture_settings.page_guard_align_buffer_sizes = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_copy_on_map"))
    {
        settings_struct_.capture_settings.page_guard_copy_on_map = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_persistent_memory"))
    {
        settings_struct_.capture_settings.page_guard_persistent_memory = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_separate_read"))
    {
        settings_struct_.capture_settings.page_guard_separate_read = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_signal_handler_watcher"))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_signal_handler_watcher_max_restores"))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher_max_restores = atoi(value.c_str());
    }
    else if (!key.compare("page_guard_unblock_sigsegv"))
    {
        settings_struct_.capture_settings.page_guard_unblock_sigsegv = SettingValueToBool(value);
    }
    else if (!key.compare("queue_zero_only"))
    {
        settings_struct_.capture_settings.queue_zero_only = SettingValueToBool(value);
    }
    else if (!key.compare("quit_after_capture_frames"))
    {
        settings_struct_.capture_settings.quit_after_capture_frames = SettingValueToBool(value);
    }
    else if (!key.compare("screenshot_dir"))
    {
        settings_struct_.capture_settings.screenshot_dir = value;
    }
    else if (!key.compare("screenshot_format"))
    {
        settings_struct_.capture_settings.screenshot_format = value;
    }
    else if (!key.compare("screenshot_frames"))
    {
        settings_struct_.capture_settings.screenshot_frames = value;
    }
    else if (!key.compare("screenshot_interval"))
    {
        settings_struct_.capture_settings.screenshot_interval = atoi(value.c_str());
    }
#if defined(__ANDROID__)
    else if (!key.compare("capture_android_dump_assets"))
    {
        settings_struct_.capture_settings.capture_android_dump_assets = SettingValueToBool(value);
    }
    else if (!key.compare("capture_android_trigger"))
    {
        settings_struct_.capture_settings.capture_android_trigger = SettingValueToBool(value);
    }
    else if (!key.compare("ignore_frame_boundary_android"))
    {
        settings_struct_.capture_settings.ignore_frame_boundary_android = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_track_ahb_memory"))
    {
        settings_struct_.capture_settings.page_guard_track_ahb_memory = SettingValueToBool(value);
    }
#endif // defined(__ANDROID__)
#if defined(__linux__)
    else if (!key.compare("capture_environment"))
    {
        settings_struct_.capture_settings.capture_environment = value;
    }
    else if (!key.compare("capture_trigger"))
    {
        settings_struct_.capture_settings.capture_trigger = value;
    }
#endif // defined(__linux__)
#if defined(__APPLE__)
    else if (!key.compare("capture_environment"))
    {
        settings_struct_.capture_settings.capture_environment = value;
    }
    else if (!key.compare("capture_trigger"))
    {
        settings_struct_.capture_settings.capture_trigger = value;
    }
#endif // defined(__APPLE__)
#if defined(WIN32)
    else if (!key.compare("capture_environment"))
    {
        settings_struct_.capture_settings.capture_environment = value;
    }
    else if (!key.compare("capture_trigger"))
    {
        settings_struct_.capture_settings.capture_trigger = value;
    }
    else if (!key.compare("log_output_to_os_debug_string"))
    {
        settings_struct_.capture_settings.log_output_to_os_debug_string = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_external_memory"))
    {
        settings_struct_.capture_settings.page_guard_external_memory = SettingValueToBool(value);
    }
#endif // defined(WIN32)
    else
    {
        GFXRECON_LOG_ERROR("Failed to find setting associated with key %s", key.c_str());
    }
}


// This functions checks for any possible environment variables that GFXR cares about,
// based on the type of tool running, and adjusts the corresponding setting value
// based on what is read, if valid.
void SettingsManager::ReadEnvironmentVariables()
{
    std::string env_var_value;

    // -- Capture-specific
    if (ReadEnvironmentVariable("accel_struct_padding", env_var_value))
    {
        settings_struct_.capture_settings.accel_struct_padding = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("allow_pipeline_compile_required", env_var_value))
    {
        settings_struct_.capture_settings.allow_pipeline_compile_required = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_compression_type", env_var_value))
    {
        settings_struct_.capture_settings.capture_compression_type = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_draw_calls", env_var_value))
    {
        settings_struct_.capture_settings.capture_draw_calls = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_file", env_var_value))
    {
        settings_struct_.capture_settings.capture_file = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_file_flush", env_var_value))
    {
        settings_struct_.capture_settings.capture_file_flush = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_file_timestamp", env_var_value))
    {
        settings_struct_.capture_settings.capture_file_timestamp = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_frames", env_var_value))
    {
        settings_struct_.capture_settings.capture_frames = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_iunknown_wrapping", env_var_value))
    {
        settings_struct_.capture_settings.capture_iunknown_wrapping = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_process_name", env_var_value))
    {
        settings_struct_.capture_settings.capture_process_name = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_queue_submits", env_var_value))
    {
        settings_struct_.capture_settings.capture_queue_submits = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_dynamic_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_dynamic_trigger_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger_dump_assets = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_trigger_frames", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger_frames = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_use_asset_file", env_var_value))
    {
        settings_struct_.capture_settings.capture_use_asset_file = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("debug_device_lost", env_var_value))
    {
        settings_struct_.capture_settings.debug_device_lost = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("debug_layer", env_var_value))
    {
        settings_struct_.capture_settings.debug_layer = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("disable_dxr", env_var_value))
    {
        settings_struct_.capture_settings.disable_dxr = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("disable_meta_command", env_var_value))
    {
        settings_struct_.capture_settings.disable_meta_command = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("force_command_serialization", env_var_value))
    {
        settings_struct_.capture_settings.force_command_serialization = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("force_fifo_present_mode", env_var_value))
    {
        settings_struct_.capture_settings.force_fifo_present_mode = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_allow_indents", env_var_value))
    {
        settings_struct_.capture_settings.log_allow_indents = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_break_on_error", env_var_value))
    {
        settings_struct_.capture_settings.log_break_on_error = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_detailed", env_var_value))
    {
        settings_struct_.capture_settings.log_detailed = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_errors_to_stderr", env_var_value))
    {
        settings_struct_.capture_settings.log_errors_to_stderr = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_file", env_var_value))
    {
        settings_struct_.capture_settings.log_file = env_var_value;
    }
    if (ReadEnvironmentVariable("log_file_create_new", env_var_value))
    {
        settings_struct_.capture_settings.log_file_create_new = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_file_flush_after_write", env_var_value))
    {
        settings_struct_.capture_settings.log_file_flush_after_write = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_file_keep_open", env_var_value))
    {
        settings_struct_.capture_settings.log_file_keep_open = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_level", env_var_value))
    {
        settings_struct_.capture_settings.log_level = env_var_value;
    }
    if (ReadEnvironmentVariable("log_output_to_console", env_var_value))
    {
        settings_struct_.capture_settings.log_output_to_console = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_timestamps", env_var_value))
    {
        settings_struct_.capture_settings.log_timestamps = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("memory_tracking_mode", env_var_value))
    {
        settings_struct_.capture_settings.memory_tracking_mode = env_var_value;
    }
    if (ReadEnvironmentVariable("page_guard_align_buffer_sizes", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_align_buffer_sizes = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_copy_on_map", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_copy_on_map = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_persistent_memory", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_persistent_memory = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_separate_read", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_separate_read = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_signal_handler_watcher", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_signal_handler_watcher_max_restores", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher_max_restores = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("page_guard_unblock_sigsegv", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_unblock_sigsegv = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("queue_zero_only", env_var_value))
    {
        settings_struct_.capture_settings.queue_zero_only = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("quit_after_capture_frames", env_var_value))
    {
        settings_struct_.capture_settings.quit_after_capture_frames = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("rv_annotation_descriptor", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_descriptor = env_var_value;
    }
    if (ReadEnvironmentVariable("rv_annotation_experimental", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_experimental = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("rv_annotation_gpuva", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_gpuva = env_var_value;
    }
    if (ReadEnvironmentVariable("rv_annotation_rand", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_rand = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("screenshot_dir", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_dir = env_var_value;
    }
    if (ReadEnvironmentVariable("screenshot_format", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_format = env_var_value;
    }
    if (ReadEnvironmentVariable("screenshot_frames", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_frames = env_var_value;
    }
    if (ReadEnvironmentVariable("screenshot_interval", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_interval = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("skip_threads_with_invalid_data", env_var_value))
    {
        settings_struct_.capture_settings.skip_threads_with_invalid_data = SettingValueToBool(env_var_value);
    }
#if defined(__ANDROID__)
    if (ReadEnvironmentVariable("capture_android_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_dump_assets = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_android_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_trigger = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("ignore_frame_boundary_android", env_var_value))
    {
        settings_struct_.capture_settings.ignore_frame_boundary_android = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_track_ahb_memory", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_track_ahb_memory = SettingValueToBool(env_var_value);
    }
#endif // defined(__ANDROID__)
#if defined(__linux__)
    if (ReadEnvironmentVariable("capture_environment", env_var_value))
    {
        settings_struct_.capture_settings.capture_environment = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger = env_var_value;
    }
#endif // defined(__linux__)
#if defined(__APPLE__)
    if (ReadEnvironmentVariable("capture_environment", env_var_value))
    {
        settings_struct_.capture_settings.capture_environment = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger = env_var_value;
    }
#endif // defined(__APPLE__)
#if defined(WIN32)
    if (ReadEnvironmentVariable("capture_environment", env_var_value))
    {
        settings_struct_.capture_settings.capture_environment = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger = env_var_value;
    }
    if (ReadEnvironmentVariable("log_output_to_os_debug_string", env_var_value))
    {
        settings_struct_.capture_settings.log_output_to_os_debug_string = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_external_memory", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_external_memory = SettingValueToBool(env_var_value);
    }
#endif // defined(WIN32)

    // -- Replay-specific
    if (ReadEnvironmentVariable("replay_debug_device_lost", env_var_value))
    {
        settings_struct_.replay_settings.debug_device_lost = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_log_file", env_var_value))
    {
        settings_struct_.replay_settings.log_file = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_log_level", env_var_value))
    {
        settings_struct_.replay_settings.log_level = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_log_timestamps", env_var_value))
    {
        settings_struct_.replay_settings.log_timestamps = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_screenshot_dir", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_dir = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_format", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_format = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshots", env_var_value))
    {
        settings_struct_.replay_settings.screenshots = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_interval", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_interval = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_add_new_pipeline_caches", env_var_value))
    {
        settings_struct_.replay_settings.add_new_pipeline_caches = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_capture", env_var_value))
    {
        settings_struct_.replay_settings.capture = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_cpu_mask", env_var_value))
    {
        settings_struct_.replay_settings.cpu_mask = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_debug_messenger_level", env_var_value))
    {
        settings_struct_.replay_settings.debug_messenger_level = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_deduplicate_device", env_var_value))
    {
        settings_struct_.replay_settings.deduplicate_device = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_discard_cached_psos", env_var_value))
    {
        settings_struct_.replay_settings.discard_cached_psos = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_before_draw", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_before_draw = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_binary_file_compression_type", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_binary_file_compression_type = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dir", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dir = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_all_image_subresources", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_all_image_subresources = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_build_acceleration_structures_input_buffers", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_build_acceleration_structures_input_buffers = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_color_attachment_index", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_color_attachment_index = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_depth_attachment", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_depth_attachment = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_raw_images", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_raw_images = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_separate_alpha", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_separate_alpha = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_unused_vertex_bindings", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_unused_vertex_bindings = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_vertex_index_buffers", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_vertex_index_buffers = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_image_format", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_image_format = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_json_output_per_command", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_json_output_per_command = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_modifiable_state_only", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_modifiable_state_only = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_scale", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_scale = static_cast<float>(atof(env_var_value.c_str()));
    }
    if (ReadEnvironmentVariable("replay_dx12_ags_inject_markers", env_var_value))
    {
        settings_struct_.replay_settings.dx12_ags_inject_markers = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dx12_override_object_names", env_var_value))
    {
        settings_struct_.replay_settings.dx12_override_object_names = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dx12_two_pass_replay", env_var_value))
    {
        settings_struct_.replay_settings.dx12_two_pass_replay = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_flush_inside_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.flush_inside_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_flush_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.flush_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_gpu", env_var_value))
    {
        settings_struct_.replay_settings.gpu = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_gpu_group", env_var_value))
    {
        settings_struct_.replay_settings.gpu_group = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_help", env_var_value))
    {
        settings_struct_.replay_settings.help = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_input_capture", env_var_value))
    {
        settings_struct_.replay_settings.input_capture = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_load_pipeline_cache", env_var_value))
    {
        settings_struct_.replay_settings.load_pipeline_cache = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_log_debugview", env_var_value))
    {
        settings_struct_.replay_settings.log_debugview = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_measurement_file", env_var_value))
    {
        settings_struct_.replay_settings.measurement_file = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_measurement_frame_range", env_var_value))
    {
        settings_struct_.replay_settings.measurement_frame_range = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_memory_translation", env_var_value))
    {
        settings_struct_.replay_settings.memory_translation = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_offscreen_swapchain_frame_boundary", env_var_value))
    {
        settings_struct_.replay_settings.offscreen_swapchain_frame_boundary = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_omit_pipeline_cache_data", env_var_value))
    {
        settings_struct_.replay_settings.omit_pipeline_cache_data = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_pause_frame", env_var_value))
    {
        settings_struct_.replay_settings.pause_frame = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_paused", env_var_value))
    {
        settings_struct_.replay_settings.paused = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_pbi_all", env_var_value))
    {
        settings_struct_.replay_settings.pbi_all = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_pbis", env_var_value))
    {
        settings_struct_.replay_settings.pbis = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_pipeline_creation_jobs", env_var_value))
    {
        settings_struct_.replay_settings.pipeline_creation_jobs = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_preload_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.preload_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_present_mode", env_var_value))
    {
        settings_struct_.replay_settings.present_mode = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_quit_after_frame", env_var_value))
    {
        settings_struct_.replay_settings.quit_after_frame = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_quit_after_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.quit_after_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_remove_unsupported", env_var_value))
    {
        settings_struct_.replay_settings.remove_unsupported = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_replace_shaders", env_var_value))
    {
        settings_struct_.replay_settings.replace_shaders = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_save_pipeline_cache", env_var_value))
    {
        settings_struct_.replay_settings.save_pipeline_cache = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_all", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_all = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_screenshot_ignore_FrameBoundaryANDROID", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_ignore_FrameBoundaryANDROID = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_screenshot_prefix", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_prefix = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_scale", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_scale = static_cast<float>(atof(env_var_value.c_str()));
    }
    if (ReadEnvironmentVariable("replay_screenshot_size", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_size = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_skip_failed_allocations", env_var_value))
    {
        settings_struct_.replay_settings.skip_failed_allocations = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_skip_get_fence_ranges", env_var_value))
    {
        settings_struct_.replay_settings.skip_get_fence_ranges = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_skip_get_fence_status", env_var_value))
    {
        settings_struct_.replay_settings.skip_get_fence_status = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_surface_index", env_var_value))
    {
        settings_struct_.replay_settings.surface_index = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_swapchain", env_var_value))
    {
        settings_struct_.replay_settings.swapchain = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_sync", env_var_value))
    {
        settings_struct_.replay_settings.sync = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_use_captured_swapchain_indices", env_var_value))
    {
        settings_struct_.replay_settings.use_captured_swapchain_indices = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_use_colorspace_fallback", env_var_value))
    {
        settings_struct_.replay_settings.use_colorspace_fallback = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_validate", env_var_value))
    {
        settings_struct_.replay_settings.validate = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_version", env_var_value))
    {
        settings_struct_.replay_settings.version = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_virtual_swapchain_skip_blit", env_var_value))
    {
        settings_struct_.replay_settings.virtual_swapchain_skip_blit = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_wait_before_present", env_var_value))
    {
        settings_struct_.replay_settings.wait_before_present = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_wsi", env_var_value))
    {
        settings_struct_.replay_settings.wsi = env_var_value;
    }
#if defined(__ANDROID__)
    if (ReadEnvironmentVariable("replay_omit_null_hardware_buffers", env_var_value))
    {
        settings_struct_.replay_settings.omit_null_hardware_buffers = SettingValueToBool(env_var_value);
    }
#endif // defined(__ANDROID__)
#if defined(WIN32)
    if (ReadEnvironmentVariable("replay_allowed_messages", env_var_value))
    {
        settings_struct_.replay_settings.allowed_messages = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_batching_memory_usage", env_var_value))
    {
        settings_struct_.replay_settings.batching_memory_usage = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_create_dummy_allocations", env_var_value))
    {
        settings_struct_.replay_settings.create_dummy_allocations = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_denied_messages", env_var_value))
    {
        settings_struct_.replay_settings.denied_messages = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_force_windowed", env_var_value))
    {
        settings_struct_.replay_settings.force_windowed = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_force_windowed_origin", env_var_value))
    {
        settings_struct_.replay_settings.force_windowed_origin = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_no_debug_popup", env_var_value))
    {
        settings_struct_.replay_settings.no_debug_popup = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_use_cached_psos", env_var_value))
    {
        settings_struct_.replay_settings.use_cached_psos = SettingValueToBool(env_var_value);
    }
#endif // defined(WIN32)
}


// This functions checks only environment variables that may change dynamically,
// based on the type of tool running, and adjusts the corresponding setting value
// based on what is read, if valid.
void SettingsManager::UpdateDynamicEnvironmentVariables()
{
    std::string env_var_value;

    // -- Capture-specific
    if (ReadEnvironmentVariable("capture_dynamic_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_dynamic_trigger_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger_dump_assets = SettingValueToBool(env_var_value);
    }
#if defined(__ANDROID__)
    if (ReadEnvironmentVariable("capture_android_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_dump_assets = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_android_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_trigger = SettingValueToBool(env_var_value);
    }
#endif // defined(__ANDROID__)

    // -- Replay-specific
}

