
/*
 * Copyright (c) 2025-2026 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

// clang-format off


// This functions takes in a settings key value and a string from the Vulkan settings file
// and attempts to update the setting value associated with the key.
void SettingsManager::AdjustSettingFromFile(const std::string& key,
                                            const std::string& value)
{
    if (!key.compare("allow_pipeline_compile_required"))
    {
        settings_struct_.capture_settings.allow_pipeline_compile_required = SettingValueToBool(value);
    }
    else if (!key.compare("capture_compression_type"))
    {
        settings_struct_.capture_settings.capture_compression_type = value;
    }
    else if (!key.compare("capture_file"))
    {
        settings_struct_.capture_settings.capture_file = value;
    }
    else if (!key.compare("capture_file_flush"))
    {
        settings_struct_.capture_settings.capture_file_flush = SettingValueToBool(value);
    }
    else if (!key.compare("capture_file_timestamp"))
    {
        settings_struct_.capture_settings.capture_file_timestamp = SettingValueToBool(value);
    }
    else if (!key.compare("capture_frames"))
    {
        settings_struct_.capture_settings.capture_frames = value;
    }
    else if (!key.compare("capture_process_name"))
    {
        settings_struct_.capture_settings.capture_process_name = value;
    }
    else if (!key.compare("capture_queue_submits"))
    {
        settings_struct_.capture_settings.capture_queue_submits = value;
    }
    else if (!key.compare("capture_dynamic_trigger"))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger = SettingValueToBool(value);
    }
    else if (!key.compare("capture_dynamic_trigger_dump_assets"))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger_dump_assets = SettingValueToBool(value);
    }
    else if (!key.compare("capture_trigger_frames"))
    {
        settings_struct_.capture_settings.capture_trigger_frames = value;
    }
    else if (!key.compare("capture_use_asset_file"))
    {
        settings_struct_.capture_settings.capture_use_asset_file = SettingValueToBool(value);
    }
    else if (!key.compare("force_command_serialization"))
    {
        settings_struct_.capture_settings.force_command_serialization = SettingValueToBool(value);
    }
    else if (!key.compare("force_fifo_present_mode"))
    {
        settings_struct_.capture_settings.force_fifo_present_mode = SettingValueToBool(value);
    }
    else if (!key.compare("log_allow_indents"))
    {
        settings_struct_.capture_settings.log_allow_indents = SettingValueToBool(value);
    }
    else if (!key.compare("log_break_on_error"))
    {
        settings_struct_.capture_settings.log_break_on_error = SettingValueToBool(value);
    }
    else if (!key.compare("log_detailed"))
    {
        settings_struct_.capture_settings.log_detailed = SettingValueToBool(value);
    }
    else if (!key.compare("log_errors_to_stderr"))
    {
        settings_struct_.capture_settings.log_errors_to_stderr = SettingValueToBool(value);
    }
    else if (!key.compare("log_file"))
    {
        settings_struct_.capture_settings.log_file = value;
    }
    else if (!key.compare("log_file_create_new"))
    {
        settings_struct_.capture_settings.log_file_create_new = SettingValueToBool(value);
    }
    else if (!key.compare("log_file_flush_after_write"))
    {
        settings_struct_.capture_settings.log_file_flush_after_write = SettingValueToBool(value);
    }
    else if (!key.compare("log_file_keep_open"))
    {
        settings_struct_.capture_settings.log_file_keep_open = SettingValueToBool(value);
    }
    else if (!key.compare("log_level"))
    {
        settings_struct_.capture_settings.log_level = value;
    }
    else if (!key.compare("log_output_to_console"))
    {
        settings_struct_.capture_settings.log_output_to_console = SettingValueToBool(value);
    }
    else if (!key.compare("log_timestamps"))
    {
        settings_struct_.capture_settings.log_timestamps = SettingValueToBool(value);
    }
    else if (!key.compare("memory_tracking_mode"))
    {
        settings_struct_.capture_settings.memory_tracking_mode = value;
    }
    else if (!key.compare("page_guard_align_buffer_sizes"))
    {
        settings_struct_.capture_settings.page_guard_align_buffer_sizes = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_copy_on_map"))
    {
        settings_struct_.capture_settings.page_guard_copy_on_map = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_persistent_memory"))
    {
        settings_struct_.capture_settings.page_guard_persistent_memory = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_separate_read"))
    {
        settings_struct_.capture_settings.page_guard_separate_read = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_signal_handler_watcher"))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_signal_handler_watcher_max_restores"))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher_max_restores = atoi(value.c_str());
    }
    else if (!key.compare("page_guard_unblock_sigsegv"))
    {
        settings_struct_.capture_settings.page_guard_unblock_sigsegv = SettingValueToBool(value);
    }
    else if (!key.compare("queue_zero_only"))
    {
        settings_struct_.capture_settings.queue_zero_only = SettingValueToBool(value);
    }
    else if (!key.compare("quit_after_capture_frames"))
    {
        settings_struct_.capture_settings.quit_after_capture_frames = SettingValueToBool(value);
    }
    else if (!key.compare("screenshot_dir"))
    {
        settings_struct_.capture_settings.screenshot_dir = value;
    }
    else if (!key.compare("screenshot_format"))
    {
        settings_struct_.capture_settings.screenshot_format = value;
    }
    else if (!key.compare("screenshot_frames"))
    {
        settings_struct_.capture_settings.screenshot_frames = value;
    }
    else if (!key.compare("screenshot_interval"))
    {
        settings_struct_.capture_settings.screenshot_interval = atoi(value.c_str());
    }
#if defined(__ANDROID__)
    else if (!key.compare("capture_android_dump_assets"))
    {
        settings_struct_.capture_settings.capture_android_dump_assets = SettingValueToBool(value);
    }
    else if (!key.compare("capture_android_trigger"))
    {
        settings_struct_.capture_settings.capture_android_trigger = SettingValueToBool(value);
    }
    else if (!key.compare("ignore_frame_boundary_android"))
    {
        settings_struct_.capture_settings.ignore_frame_boundary_android = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_track_ahb_memory"))
    {
        settings_struct_.capture_settings.page_guard_track_ahb_memory = SettingValueToBool(value);
    }
#endif // defined(__ANDROID__)
#if defined(__linux__)
    else if (!key.compare("capture_environment"))
    {
        settings_struct_.capture_settings.capture_environment = value;
    }
    else if (!key.compare("capture_trigger"))
    {
        settings_struct_.capture_settings.capture_trigger = value;
    }
#endif // defined(__linux__)
#if defined(__APPLE__)
    else if (!key.compare("capture_environment"))
    {
        settings_struct_.capture_settings.capture_environment = value;
    }
    else if (!key.compare("capture_trigger"))
    {
        settings_struct_.capture_settings.capture_trigger = value;
    }
#endif // defined(__APPLE__)
#if defined(WIN32)
    else if (!key.compare("capture_environment"))
    {
        settings_struct_.capture_settings.capture_environment = value;
    }
    else if (!key.compare("capture_trigger"))
    {
        settings_struct_.capture_settings.capture_trigger = value;
    }
    else if (!key.compare("log_output_to_os_debug_string"))
    {
        settings_struct_.capture_settings.log_output_to_os_debug_string = SettingValueToBool(value);
    }
    else if (!key.compare("page_guard_external_memory"))
    {
        settings_struct_.capture_settings.page_guard_external_memory = SettingValueToBool(value);
    }
#endif // defined(WIN32)
    else
    {
        GFXRECON_LOG_ERROR("Failed to find setting associated with key %s", key.c_str());
    }
}


// This functions checks for any possible environment variables that GFXR cares about,
// based on the type of tool running, and adjusts the corresponding setting value
// based on what is read, if valid.
void SettingsManager::ReadEnvironmentVariables()
{
    std::string env_var_value;

    // -- Capture-specific
    if (ReadEnvironmentVariable("accel_struct_padding", env_var_value))
    {
        settings_struct_.capture_settings.accel_struct_padding = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("allow_pipeline_compile_required", env_var_value))
    {
        settings_struct_.capture_settings.allow_pipeline_compile_required = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_compression_type", env_var_value))
    {
        settings_struct_.capture_settings.capture_compression_type = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_draw_calls", env_var_value))
    {
        settings_struct_.capture_settings.capture_draw_calls = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_file", env_var_value))
    {
        settings_struct_.capture_settings.capture_file = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_file_flush", env_var_value))
    {
        settings_struct_.capture_settings.capture_file_flush = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_file_timestamp", env_var_value))
    {
        settings_struct_.capture_settings.capture_file_timestamp = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_frames", env_var_value))
    {
        settings_struct_.capture_settings.capture_frames = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_iunknown_wrapping", env_var_value))
    {
        settings_struct_.capture_settings.capture_iunknown_wrapping = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_process_name", env_var_value))
    {
        settings_struct_.capture_settings.capture_process_name = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_queue_submits", env_var_value))
    {
        settings_struct_.capture_settings.capture_queue_submits = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_dynamic_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_dynamic_trigger_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger_dump_assets = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_trigger_frames", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger_frames = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_use_asset_file", env_var_value))
    {
        settings_struct_.capture_settings.capture_use_asset_file = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("debug_device_lost", env_var_value))
    {
        settings_struct_.capture_settings.debug_device_lost = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("debug_layer", env_var_value))
    {
        settings_struct_.capture_settings.debug_layer = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("disable_dxr", env_var_value))
    {
        settings_struct_.capture_settings.disable_dxr = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("disable_meta_command", env_var_value))
    {
        settings_struct_.capture_settings.disable_meta_command = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("force_command_serialization", env_var_value))
    {
        settings_struct_.capture_settings.force_command_serialization = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("force_fifo_present_mode", env_var_value))
    {
        settings_struct_.capture_settings.force_fifo_present_mode = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_allow_indents", env_var_value))
    {
        settings_struct_.capture_settings.log_allow_indents = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_break_on_error", env_var_value))
    {
        settings_struct_.capture_settings.log_break_on_error = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_detailed", env_var_value))
    {
        settings_struct_.capture_settings.log_detailed = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_errors_to_stderr", env_var_value))
    {
        settings_struct_.capture_settings.log_errors_to_stderr = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_file", env_var_value))
    {
        settings_struct_.capture_settings.log_file = env_var_value;
    }
    if (ReadEnvironmentVariable("log_file_create_new", env_var_value))
    {
        settings_struct_.capture_settings.log_file_create_new = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_file_flush_after_write", env_var_value))
    {
        settings_struct_.capture_settings.log_file_flush_after_write = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_file_keep_open", env_var_value))
    {
        settings_struct_.capture_settings.log_file_keep_open = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_level", env_var_value))
    {
        settings_struct_.capture_settings.log_level = env_var_value;
    }
    if (ReadEnvironmentVariable("log_output_to_console", env_var_value))
    {
        settings_struct_.capture_settings.log_output_to_console = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("log_timestamps", env_var_value))
    {
        settings_struct_.capture_settings.log_timestamps = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("memory_tracking_mode", env_var_value))
    {
        settings_struct_.capture_settings.memory_tracking_mode = env_var_value;
    }
    if (ReadEnvironmentVariable("page_guard_align_buffer_sizes", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_align_buffer_sizes = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_copy_on_map", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_copy_on_map = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_persistent_memory", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_persistent_memory = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_separate_read", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_separate_read = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_signal_handler_watcher", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_signal_handler_watcher_max_restores", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_signal_handler_watcher_max_restores = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("page_guard_unblock_sigsegv", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_unblock_sigsegv = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("queue_zero_only", env_var_value))
    {
        settings_struct_.capture_settings.queue_zero_only = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("quit_after_capture_frames", env_var_value))
    {
        settings_struct_.capture_settings.quit_after_capture_frames = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("rv_annotation_descriptor", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_descriptor = env_var_value;
    }
    if (ReadEnvironmentVariable("rv_annotation_experimental", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_experimental = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("rv_annotation_gpuva", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_gpuva = env_var_value;
    }
    if (ReadEnvironmentVariable("rv_annotation_rand", env_var_value))
    {
        settings_struct_.capture_settings.rv_annotation_rand = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("screenshot_dir", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_dir = env_var_value;
    }
    if (ReadEnvironmentVariable("screenshot_format", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_format = env_var_value;
    }
    if (ReadEnvironmentVariable("screenshot_frames", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_frames = env_var_value;
    }
    if (ReadEnvironmentVariable("screenshot_interval", env_var_value))
    {
        settings_struct_.capture_settings.screenshot_interval = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("skip_threads_with_invalid_data", env_var_value))
    {
        settings_struct_.capture_settings.skip_threads_with_invalid_data = SettingValueToBool(env_var_value);
    }
#if defined(__ANDROID__)
    if (ReadEnvironmentVariable("capture_android_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_dump_assets = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_android_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_trigger = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("ignore_frame_boundary_android", env_var_value))
    {
        settings_struct_.capture_settings.ignore_frame_boundary_android = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_track_ahb_memory", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_track_ahb_memory = SettingValueToBool(env_var_value);
    }
#endif // defined(__ANDROID__)
#if defined(__linux__)
    if (ReadEnvironmentVariable("capture_environment", env_var_value))
    {
        settings_struct_.capture_settings.capture_environment = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger = env_var_value;
    }
#endif // defined(__linux__)
#if defined(__APPLE__)
    if (ReadEnvironmentVariable("capture_environment", env_var_value))
    {
        settings_struct_.capture_settings.capture_environment = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger = env_var_value;
    }
#endif // defined(__APPLE__)
#if defined(WIN32)
    if (ReadEnvironmentVariable("capture_environment", env_var_value))
    {
        settings_struct_.capture_settings.capture_environment = env_var_value;
    }
    if (ReadEnvironmentVariable("capture_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_trigger = env_var_value;
    }
    if (ReadEnvironmentVariable("log_output_to_os_debug_string", env_var_value))
    {
        settings_struct_.capture_settings.log_output_to_os_debug_string = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("page_guard_external_memory", env_var_value))
    {
        settings_struct_.capture_settings.page_guard_external_memory = SettingValueToBool(env_var_value);
    }
#endif // defined(WIN32)

    // -- Replay-specific
    if (ReadEnvironmentVariable("replay_debug_device_lost", env_var_value))
    {
        settings_struct_.replay_settings.debug_device_lost = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_log_file", env_var_value))
    {
        settings_struct_.replay_settings.log_file = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_log_level", env_var_value))
    {
        settings_struct_.replay_settings.log_level = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_log_timestamps", env_var_value))
    {
        settings_struct_.replay_settings.log_timestamps = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_screenshot_dir", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_dir = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_format", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_format = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshots", env_var_value))
    {
        settings_struct_.replay_settings.screenshots = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_interval", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_interval = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_add_new_pipeline_caches", env_var_value))
    {
        settings_struct_.replay_settings.add_new_pipeline_caches = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_capture", env_var_value))
    {
        settings_struct_.replay_settings.capture = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_cpu_mask", env_var_value))
    {
        settings_struct_.replay_settings.cpu_mask = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_debug_messenger_level", env_var_value))
    {
        settings_struct_.replay_settings.debug_messenger_level = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_deduplicate_device", env_var_value))
    {
        settings_struct_.replay_settings.deduplicate_device = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_discard_cached_psos", env_var_value))
    {
        settings_struct_.replay_settings.discard_cached_psos = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_before_draw", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_before_draw = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_binary_file_compression_type", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_binary_file_compression_type = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dir", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dir = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_all_image_subresources", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_all_image_subresources = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_build_acceleration_structures_input_buffers", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_build_acceleration_structures_input_buffers = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_color_attachment_index", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_color_attachment_index = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_depth_attachment", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_depth_attachment = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_raw_images", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_raw_images = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_separate_alpha", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_separate_alpha = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_unused_vertex_bindings", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_unused_vertex_bindings = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_dump_vertex_index_buffers", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_dump_vertex_index_buffers = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_image_format", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_image_format = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_dump_resources_json_output_per_command", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_json_output_per_command = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_modifiable_state_only", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_modifiable_state_only = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dump_resources_scale", env_var_value))
    {
        settings_struct_.replay_settings.dump_resources_scale = static_cast<float>(atof(env_var_value.c_str()));
    }
    if (ReadEnvironmentVariable("replay_dx12_ags_inject_markers", env_var_value))
    {
        settings_struct_.replay_settings.dx12_ags_inject_markers = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dx12_override_object_names", env_var_value))
    {
        settings_struct_.replay_settings.dx12_override_object_names = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_dx12_two_pass_replay", env_var_value))
    {
        settings_struct_.replay_settings.dx12_two_pass_replay = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_flush_inside_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.flush_inside_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_flush_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.flush_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_gpu", env_var_value))
    {
        settings_struct_.replay_settings.gpu = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_gpu_group", env_var_value))
    {
        settings_struct_.replay_settings.gpu_group = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_help", env_var_value))
    {
        settings_struct_.replay_settings.help = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_input_capture", env_var_value))
    {
        settings_struct_.replay_settings.input_capture = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_load_pipeline_cache", env_var_value))
    {
        settings_struct_.replay_settings.load_pipeline_cache = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_log_debugview", env_var_value))
    {
        settings_struct_.replay_settings.log_debugview = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_measurement_file", env_var_value))
    {
        settings_struct_.replay_settings.measurement_file = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_measurement_frame_range", env_var_value))
    {
        settings_struct_.replay_settings.measurement_frame_range = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_memory_translation", env_var_value))
    {
        settings_struct_.replay_settings.memory_translation = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_offscreen_swapchain_frame_boundary", env_var_value))
    {
        settings_struct_.replay_settings.offscreen_swapchain_frame_boundary = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_omit_pipeline_cache_data", env_var_value))
    {
        settings_struct_.replay_settings.omit_pipeline_cache_data = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_pause_frame", env_var_value))
    {
        settings_struct_.replay_settings.pause_frame = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_paused", env_var_value))
    {
        settings_struct_.replay_settings.paused = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_pbi_all", env_var_value))
    {
        settings_struct_.replay_settings.pbi_all = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_pbis", env_var_value))
    {
        settings_struct_.replay_settings.pbis = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_pipeline_creation_jobs", env_var_value))
    {
        settings_struct_.replay_settings.pipeline_creation_jobs = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_preload_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.preload_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_present_mode", env_var_value))
    {
        settings_struct_.replay_settings.present_mode = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_quit_after_frame", env_var_value))
    {
        settings_struct_.replay_settings.quit_after_frame = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_quit_after_measurement_range", env_var_value))
    {
        settings_struct_.replay_settings.quit_after_measurement_range = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_remove_unsupported", env_var_value))
    {
        settings_struct_.replay_settings.remove_unsupported = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_replace_shaders", env_var_value))
    {
        settings_struct_.replay_settings.replace_shaders = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_save_pipeline_cache", env_var_value))
    {
        settings_struct_.replay_settings.save_pipeline_cache = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_all", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_all = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_screenshot_ignore_FrameBoundaryANDROID", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_ignore_FrameBoundaryANDROID = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_screenshot_prefix", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_prefix = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_screenshot_scale", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_scale = static_cast<float>(atof(env_var_value.c_str()));
    }
    if (ReadEnvironmentVariable("replay_screenshot_size", env_var_value))
    {
        settings_struct_.replay_settings.screenshot_size = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_skip_failed_allocations", env_var_value))
    {
        settings_struct_.replay_settings.skip_failed_allocations = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_skip_get_fence_ranges", env_var_value))
    {
        settings_struct_.replay_settings.skip_get_fence_ranges = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_skip_get_fence_status", env_var_value))
    {
        settings_struct_.replay_settings.skip_get_fence_status = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_surface_index", env_var_value))
    {
        settings_struct_.replay_settings.surface_index = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_swapchain", env_var_value))
    {
        settings_struct_.replay_settings.swapchain = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_sync", env_var_value))
    {
        settings_struct_.replay_settings.sync = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_use_captured_swapchain_indices", env_var_value))
    {
        settings_struct_.replay_settings.use_captured_swapchain_indices = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_use_colorspace_fallback", env_var_value))
    {
        settings_struct_.replay_settings.use_colorspace_fallback = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_validate", env_var_value))
    {
        settings_struct_.replay_settings.validate = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_version", env_var_value))
    {
        settings_struct_.replay_settings.version = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_virtual_swapchain_skip_blit", env_var_value))
    {
        settings_struct_.replay_settings.virtual_swapchain_skip_blit = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_wait_before_present", env_var_value))
    {
        settings_struct_.replay_settings.wait_before_present = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_wsi", env_var_value))
    {
        settings_struct_.replay_settings.wsi = env_var_value;
    }
#if defined(__ANDROID__)
    if (ReadEnvironmentVariable("replay_omit_null_hardware_buffers", env_var_value))
    {
        settings_struct_.replay_settings.omit_null_hardware_buffers = SettingValueToBool(env_var_value);
    }
#endif // defined(__ANDROID__)
#if defined(WIN32)
    if (ReadEnvironmentVariable("replay_allowed_messages", env_var_value))
    {
        settings_struct_.replay_settings.allowed_messages = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_batching_memory_usage", env_var_value))
    {
        settings_struct_.replay_settings.batching_memory_usage = atoi(env_var_value.c_str());
    }
    if (ReadEnvironmentVariable("replay_create_dummy_allocations", env_var_value))
    {
        settings_struct_.replay_settings.create_dummy_allocations = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_denied_messages", env_var_value))
    {
        settings_struct_.replay_settings.denied_messages = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_force_windowed", env_var_value))
    {
        settings_struct_.replay_settings.force_windowed = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_force_windowed_origin", env_var_value))
    {
        settings_struct_.replay_settings.force_windowed_origin = env_var_value;
    }
    if (ReadEnvironmentVariable("replay_no_debug_popup", env_var_value))
    {
        settings_struct_.replay_settings.no_debug_popup = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("replay_use_cached_psos", env_var_value))
    {
        settings_struct_.replay_settings.use_cached_psos = SettingValueToBool(env_var_value);
    }
#endif // defined(WIN32)
}


// This functions checks only environment variables that may change dynamically,
// based on the type of tool running, and adjusts the corresponding setting value
// based on what is read, if valid.
void SettingsManager::UpdateDynamicEnvironmentVariables()
{
    std::string env_var_value;

    // -- Capture-specific
    if (ReadEnvironmentVariable("capture_dynamic_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_dynamic_trigger_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_dynamic_trigger_dump_assets = SettingValueToBool(env_var_value);
    }
#if defined(__ANDROID__)
    if (ReadEnvironmentVariable("capture_android_dump_assets", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_dump_assets = SettingValueToBool(env_var_value);
    }
    if (ReadEnvironmentVariable("capture_android_trigger", env_var_value))
    {
        settings_struct_.capture_settings.capture_android_trigger = SettingValueToBool(env_var_value);
    }
#endif // defined(__ANDROID__)

    // -- Replay-specific
}

bool SettingsManager::ProcessOptionArgument(GfxrToolType                    tool_type,
                                            const std::vector<std::string>& command_line_args,
                                            size_t&                         cur_arg)
{
    bool valid_arg = false;

    // If this is a string or a single char
    if (command_line_args[cur_arg].size() == 2)
    {
        if (tool_type == kGfxrToolType_Replay_Tool)
        {
            switch (command_line_args[cur_arg].at(1))
            {
                default:
                    GFXRECON_LOG_WARNING("Invalid argument %s", command_line_args[cur_arg].c_str());
                    valid_arg = false;
                    break;
                case ('h'):
                    settings_struct_.replay_settings.help = true;
                    valid_arg = true;
                    break;
                case ('m'):
                    if (HasArgumentParameter(command_line_args, cur_arg))
                    {
                        settings_struct_.replay_settings.memory_translation = command_line_args[++cur_arg];
                        valid_arg = true;
                    }
                    else
                    {
                        GFXRECON_LOG_ERROR("Command-line argument 'm' missing expected argument");
                    }
                    break;
            }
        }
    }
    else
    {
        // Get the string after the last dash
        std::string arg_opt = command_line_args[cur_arg].substr(2);
        if (tool_type == kGfxrToolType_Replay_Tool)
        {
            if (arg_opt == "log-file")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.log_file = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"log-file\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "log-level")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.log_level = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"log-level\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "log-timestamps")
            {
                settings_struct_.replay_settings.log_timestamps = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "screenshot-dir")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshot_dir = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshot-dir\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "screenshot-format")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshot_format = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshot-format\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "screenshots")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshots = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshots\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "screenshot-interval")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshot_interval = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshot-interval\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "add-new-pipeline-caches")
            {
                settings_struct_.replay_settings.add_new_pipeline_caches = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "capture")
            {
                settings_struct_.replay_settings.capture = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "cpu-mask")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.cpu_mask = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"cpu-mask\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "debug-messenger-level")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.debug_messenger_level = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"debug-messenger-level\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "deduplicate-device")
            {
                settings_struct_.replay_settings.deduplicate_device = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.dump_resources = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"dump-resources\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "dump-resources-before-draw")
            {
                settings_struct_.replay_settings.dump_resources_before_draw = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dir")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.dump_resources_dir = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"dump-resources-dir\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-all-image-subresources")
            {
                settings_struct_.replay_settings.dump_resources_dump_all_image_subresources = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-build-acceleration-structures-input-buffers")
            {
                settings_struct_.replay_settings.dump_resources_dump_build_acceleration_structures_input_buffers = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-color-attachment-index")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.dump_resources_dump_color_attachment_index = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"dump-resources-dump-color-attachment-index\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-depth-attachment")
            {
                settings_struct_.replay_settings.dump_resources_dump_depth_attachment = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-raw-images")
            {
                settings_struct_.replay_settings.dump_resources_dump_raw_images = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-separate-alpha")
            {
                settings_struct_.replay_settings.dump_resources_dump_separate_alpha = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-unused-vertex-bindings")
            {
                settings_struct_.replay_settings.dump_resources_dump_unused_vertex_bindings = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-dump-vertex-index-buffers")
            {
                settings_struct_.replay_settings.dump_resources_dump_vertex_index_buffers = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-image-format")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.dump_resources_image_format = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"dump-resources-image-format\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "dump-resources-json-output-per-command")
            {
                settings_struct_.replay_settings.dump_resources_json_output_per_command = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-scale")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.dump_resources_scale = static_cast<float>(atof(command_line_args[++cur_arg].c_str()));
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"dump-resources-scale\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "flush-inside-measurement-range")
            {
                settings_struct_.replay_settings.flush_inside_measurement_range = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "fmr" || arg_opt == "flush-measurement-range")
            {
                settings_struct_.replay_settings.flush_measurement_range = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "gpu")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.gpu = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"gpu\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "gpu-group")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.gpu_group = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"gpu-group\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "help")
            {
                settings_struct_.replay_settings.help = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "input-capture")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.input_capture = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"input-capture\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "load-pipeline-cache")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.load_pipeline_cache = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"load-pipeline-cache\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "log-debugview")
            {
                settings_struct_.replay_settings.log_debugview = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "measurement-file")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.measurement_file = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"measurement-file\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "mfr" || arg_opt == "measurement-frame-range")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.measurement_frame_range = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"mfr|measurement-frame-range\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "memory-translation")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.memory_translation = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"memory-translation\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "offscreen-swapchain-frame-boundary")
            {
                settings_struct_.replay_settings.offscreen_swapchain_frame_boundary = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "opcd" || arg_opt == "omit-pipeline-cache-data")
            {
                settings_struct_.replay_settings.omit_pipeline_cache_data = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "pause-frame")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.pause_frame = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"pause-frame\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "paused")
            {
                settings_struct_.replay_settings.paused = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "pbi-all")
            {
                settings_struct_.replay_settings.pbi_all = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "pbis")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.pbis = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"pbis\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "pcj" || arg_opt == "pipeline-creation-jobs")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.pipeline_creation_jobs = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"pcj|pipeline-creation-jobs\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "preload-measurement-range")
            {
                settings_struct_.replay_settings.preload_measurement_range = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "quit-after-frame")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.quit_after_frame = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"quit-after-frame\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "qamr" || arg_opt == "quit-after-measurement-range")
            {
                settings_struct_.replay_settings.quit_after_measurement_range = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "remove-unsupported")
            {
                settings_struct_.replay_settings.remove_unsupported = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "replace-shaders")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.replace_shaders = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"replace-shaders\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "save-pipeline-cache")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.save_pipeline_cache = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"save-pipeline-cache\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "screenshot-all")
            {
                settings_struct_.replay_settings.screenshot_all = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "screenshot-ignore-FrameBoundaryANDROID")
            {
                settings_struct_.replay_settings.screenshot_ignore_FrameBoundaryANDROID = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "screenshot-prefix")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshot_prefix = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshot-prefix\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "screenshot-scale")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshot_scale = static_cast<float>(atof(command_line_args[++cur_arg].c_str()));
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshot-scale\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "screenshot-size")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.screenshot_size = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"screenshot-size\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "sfa" || arg_opt == "skip-failed-allocations")
            {
                settings_struct_.replay_settings.skip_failed_allocations = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "swapchain")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.swapchain = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"swapchain\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "sync")
            {
                settings_struct_.replay_settings.sync = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "use-captured-swapchain-indices")
            {
                settings_struct_.replay_settings.use_captured_swapchain_indices = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "use-colorspace-fallback")
            {
                settings_struct_.replay_settings.use_colorspace_fallback = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "validate")
            {
                settings_struct_.replay_settings.validate = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "version")
            {
                settings_struct_.replay_settings.version = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "vssb" || arg_opt == "virtual-swapchain-skip-blit")
            {
                settings_struct_.replay_settings.virtual_swapchain_skip_blit = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "wait-before-present")
            {
                settings_struct_.replay_settings.wait_before_present = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "wsi")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.wsi = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"wsi\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "debug-device-lost")
            {
                settings_struct_.replay_settings.debug_device_lost = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dcp" || arg_opt == "discard-cached-psos")
            {
                settings_struct_.replay_settings.discard_cached_psos = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dump-resources-modifiable-state-only")
            {
                settings_struct_.replay_settings.dump_resources_modifiable_state_only = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dx12-ags-inject-markers")
            {
                settings_struct_.replay_settings.dx12_ags_inject_markers = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dx12-override-object-names")
            {
                settings_struct_.replay_settings.dx12_override_object_names = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "dx12-two-pass-replay")
            {
                settings_struct_.replay_settings.dx12_two_pass_replay = true;
                valid_arg = true;
                goto early_out;
            }
#if defined(WIN32)
            if (arg_opt == "allowed-messages")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.allowed_messages = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"allowed-messages\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "batching-memory-usage")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.batching_memory_usage = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"batching-memory-usage\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "denied-messages")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.denied_messages = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"denied-messages\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "fw" || arg_opt == "force-windowed")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.force_windowed = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"fw|force-windowed\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "fwo" || arg_opt == "force-windowed-origin")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.force_windowed_origin = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"fwo|force-windowed-origin\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "use-cached-psos")
            {
                settings_struct_.replay_settings.use_cached_psos = true;
                valid_arg = true;
                goto early_out;
            }
#endif // defined(WIN32)
            if (arg_opt == "dump-resources-binary-file-compression-type")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.dump_resources_binary_file_compression_type = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"dump-resources-binary-file-compression-type\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "present-mode")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.present_mode = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"present-mode\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "sgfr" || arg_opt == "skip-get-fence-ranges")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.skip_get_fence_ranges = command_line_args[++cur_arg];
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"sgfr|skip-get-fence-ranges\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "sgfs" || arg_opt == "skip-get-fence-status")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.skip_get_fence_status = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"sgfs|skip-get-fence-status\" missing expected argument");
                }
                goto early_out;
            }
            if (arg_opt == "surface-index")
            {
                if (HasArgumentParameter(command_line_args, cur_arg))
                {
                    settings_struct_.replay_settings.surface_index = atoi(command_line_args[++cur_arg].c_str());
                    valid_arg = true;
                }
                else
                {
                    GFXRECON_LOG_ERROR("Command-line argument \"surface-index\" missing expected argument");
                }
                goto early_out;
            }
#if defined(__ANDROID__)
            if (arg_opt == "onhb" || arg_opt == "omit-null-hardware-buffers")
            {
                settings_struct_.replay_settings.omit_null_hardware_buffers = true;
                valid_arg = true;
                goto early_out;
            }
#endif // defined(__ANDROID__)
#if defined(WIN32)
            if (arg_opt == "create-dummy-allocations")
            {
                settings_struct_.replay_settings.create_dummy_allocations = true;
                valid_arg = true;
                goto early_out;
            }
            if (arg_opt == "no-debug-popup")
            {
                settings_struct_.replay_settings.no_debug_popup = true;
                valid_arg = true;
                goto early_out;
            }
#endif // defined(WIN32)
        }
    }
early_out:
    return valid_arg;
}
