
/*
 * Copyright (c) 2025-2026 LunarG, Inc.
 *
 * Permission is hereby granted, free of charge, to any person obtaining a copy
 * of this software and associated documentation files (the "Software"), to
 * deal in the Software without restriction, including without limitation the
 * rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
 * sell copies of the Software, and to permit persons to whom the Software is
 * furnished to do so, subject to the following conditions:
 *
 * The above copyright notice and this permission notice shall be included in
 * all copies or substantial portions of the Software.
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
 * FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
 * IN THE SOFTWARE.
 *
 ***** WARNING **** This file is automatically generated by generate_settings.py,
 ****************** do not edit directly!
 */

#include "../tool_settings.h"

#ifndef GFXRECON_CONVERT_SETTINGS_H
#define GFXRECON_CONVERT_SETTINGS_H

static void PrintUsage(const char* exe_name)
{
    std::string app_name     = exe_name;
    size_t      dir_location = app_name.find_last_of("/\\");

    if (dir_location >= 0)
    {
        app_name.replace(0, dir_location + 1, "");
    }

    GFXRECON_WRITE_CONSOLE("\n%s - A tool to convert the contents of GFXReconstruct capture files to JSON.\n", app_name.c_str());
    GFXRECON_WRITE_CONSOLE("Usage:");

    // Generate a vector to attach all available options for this
    // current platform.  Since it can vary per platform, we do not
    // generate the strings until we take the defines into account.
    std::vector<std::string> high_level_usage;
    high_level_usage.push_back("    " + app_name + "\t");
    high_level_usage.push_back("[--log-level <level>] ");
    high_level_usage.push_back("[--expand-flags] ");
    high_level_usage.push_back("[--file-per-frame] ");
    high_level_usage.push_back("[--frame-range <N1[-N2][,...]>] ");
    high_level_usage.push_back("[--include-binaries] ");
    high_level_usage.push_back("[--output <file>] ");
    high_level_usage.push_back("[--format <format>] ");
#if defined(WIN32)
    high_level_usage.push_back("[--no-debug-popup] ");
#endif // defined(WIN32)

    high_level_usage.push_back("<file>");

    // Output the high-level usage to no more than 80 chars per line
    std::string output_string;
    const char new_line_start[] = "\t\t\t";
    for (auto& usage_item : high_level_usage)
    {
        if (output_string.length() + usage_item.length() > 80)
        {
            GFXRECON_WRITE_CONSOLE(output_string.c_str());
            output_string = new_line_start;
        }
        output_string += usage_item;
    }
    if (output_string.length() > strlen(new_line_start))
    {
       GFXRECON_WRITE_CONSOLE(output_string.c_str());
    }

    GFXRECON_WRITE_CONSOLE("\nRequired arguments:");
    GFXRECON_WRITE_CONSOLE("   <file>\t\tPath to the GFXReconstruct capture file to be converted");
    GFXRECON_WRITE_CONSOLE("        		to text");
    GFXRECON_WRITE_CONSOLE("\nOptional arguments:");
    GFXRECON_WRITE_CONSOLE("  --log-level <level>");
    GFXRECON_WRITE_CONSOLE("          \t\tSpecify the highest level message to log.  The specified");
    GFXRECON_WRITE_CONSOLE("          \t\tlevel and all levels listed after it will be enabled for");
    GFXRECON_WRITE_CONSOLE("          \t\tlogging.  For example, choosing the `warning` level will");
    GFXRECON_WRITE_CONSOLE("          \t\talso enable the `error` and `fatal` levels.");
    GFXRECON_WRITE_CONSOLE("          \t\t<level> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `debug`     Messages with debug-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `info`      Messages with info-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `warning`   Messages with warning-severity and higher");
    GFXRECON_WRITE_CONSOLE("          \t\t   `error`     Only Error/Fatal messages");
    GFXRECON_WRITE_CONSOLE("          \t\t   `fatal`     Only Fatal messages");
    GFXRECON_WRITE_CONSOLE("  --expand-flags");
    GFXRECON_WRITE_CONSOLE("          \t\tPrint flags values from Vulkan traces with its");
    GFXRECON_WRITE_CONSOLE("          \t\tcorrespondent symbolic representation. Otherwise, the flags");
    GFXRECON_WRITE_CONSOLE("          \t\tare printed as hexadecimal value.");
    GFXRECON_WRITE_CONSOLE("  --file-per-frame");
    GFXRECON_WRITE_CONSOLE("          \t\tCreates a new file for every frame processed. Frame number");
    GFXRECON_WRITE_CONSOLE("          \t\tis added as a suffix to the output file name.");
    GFXRECON_WRITE_CONSOLE("  --frame-range <N1[-N2][,...]>");
    GFXRECON_WRITE_CONSOLE("          \t\tFrame ranges to be converted. In order to retrieve trim");
    GFXRECON_WRITE_CONSOLE("          \t\ttrace state, frame 0 has to be in frame range. Frame ranges");
    GFXRECON_WRITE_CONSOLE("          \t\tshould be specified in ascending order and cannot overlap.");
    GFXRECON_WRITE_CONSOLE("          \t\tFrame numbering is zero-indexed and inclusive. Example:");
    GFXRECON_WRITE_CONSOLE("          \t\t0-2,5,8-10 will generate data for 7 frames.");
    GFXRECON_WRITE_CONSOLE("  --include-binaries");
    GFXRECON_WRITE_CONSOLE("          \t\tDump binaries from Vulkan traces in a separate file with an");
    GFXRECON_WRITE_CONSOLE("          \t\tunique name. The main JSON file will include a reference");
    GFXRECON_WRITE_CONSOLE("          \t\twith the file name. The binary files are dumped in a");
    GFXRECON_WRITE_CONSOLE("          \t\tsubdirectory");
    GFXRECON_WRITE_CONSOLE("  --output <file>");
    GFXRECON_WRITE_CONSOLE("          \t\tPlace extracted shaders into directory <dir>. Otherwise use");
    GFXRECON_WRITE_CONSOLE("          \t\t<file>.shaders in working directory. Create directory if");
    GFXRECON_WRITE_CONSOLE("          \t\tnecessary. Each shader is placed in individual file named");
    GFXRECON_WRITE_CONSOLE("          \t\tsh<handle_id> where handle_id is handle id of the");
    GFXRECON_WRITE_CONSOLE("          \t\tCreateShaderModule call. See gfxrecon-replay");
    GFXRECON_WRITE_CONSOLE("          \t\t--replace-shaders.");
    GFXRECON_WRITE_CONSOLE("  --format <format>");
    GFXRECON_WRITE_CONSOLE("          \t\tJSON format to write.");
    GFXRECON_WRITE_CONSOLE("          \t\t<format> may be the following:");
    GFXRECON_WRITE_CONSOLE("          \t\t   `json`      Standard JSON format (indented)");
    GFXRECON_WRITE_CONSOLE("          \t\t   `jsonl`     JSON lines format (every object in a single");
    GFXRECON_WRITE_CONSOLE("          \t\t               line)");
#if defined(WIN32)
    GFXRECON_WRITE_CONSOLE("  --no-debug-popup");
    GFXRECON_WRITE_CONSOLE("          \t\t[Windows Only] Disable the 'Abort, Retry, Ignore' message");
    GFXRECON_WRITE_CONSOLE("          \t\tbox displayed when abort() is called (Windows debug only).");
#endif // defined(WIN32)
}
#endif // GFXRECON_CONVERT_SETTINGS_H
